### ISSUE TITLE
PyCall with mayavi

### ISSUE THREAD

**Issue by simulkade** [stevengj/PyCall.jl#109]
I'm trying to use mayavi to visualize isosurfaces:

```
using PyCall
@pyimport mayavi.mlab as m
z=rand(5,5,5)
m.contour3d(z)
```

The above code works and plots the isosurfaces. But the mayavi window freezes and when I (force) close it, it kills julia. It does not happen when I use mayavi from ipython. Any idea?
Thanks in advance.

**Comment by stevengj** [comment]
Probably Mayavi is not starting its event loop for some reason.  Ideally, we can do something like PyPlot where we figure out how to hook it up to one of PyCall's event loops (since PyCall supports running the Python Tk, Qt, Gtk, and Wx event loops in the background).

**Comment by stevengj** [comment]
I'm guessing that MayaVi is somehow deciding to start in non-interactive mode and it is [waiting for you to start the Tk mainloop](http://mayavi.sourceforge.net/docs/guide/ch04.html).

**Comment by stevengj** [comment]
cc: @dlfivefifty.  Sheehan, didn't you get MayaVi working in PyCall?  What did you do?

**Comment by dlfivefifty** [comment]
Nope, it wasn't me

**Comment by simulkade** [comment]
Thanks a lot for your quick reply Steven. I followed your suggestions (I guess) and changed the code to
```
using PyCall
@pyimport mayavi.mlab as m
z=rand(5,5,5)
a = m.contour3d(z)
m.show() # just to do sth
```
and it works fine now. BTW, on my laptop (unlike my other comuter, both with same Mint 17.1 os) I ran into the same frozen window issue when calling mayavi from IPython. I had to run
```
%gui wx
```
before plotting with mayavi to solve the problem.
Thanks again for your help.

**Comment by stevengj** [comment]
It would be nicer to have a non-blocking interface similar to what you have in IPython.   If it is using the wx backend in IPython, I wonder if it is enough to do `pygui_start(:wx)` in Julia before importing mayavi?

**Comment by simulkade** [comment]
Fantastic! It works.

**Comment by stevengj** [comment]
Great!   (That is the equivalent of IPython's `%gui wx`.)
