### ISSUE TITLE
exception_access_violation

### ISSUE THREAD

**Issue by niugaust** [stevengj/PyCall.jl#111]
Hello,

I have an issue with "using PyCall" intermittently hanging.

I can do "using PyCall" in the REPL without issues. However if i have a simple script like this:

pyc.jl
- - -
println("run")
println(strftime(time()))
using PyCall
println(strftime(time()))
- - -

And call it repeatedly with a windows bat file:
loopj.bat
- - -
for /L %%A in (0,1,1000) DO julia pyc.jl
- - -

It hangs randomly after 5 or 10 iterations. Interestingly on another machine with similar configuration it runs many more iterations before also eventually hanging.

If I CTRL+C out of the hung bat file i sometimes get something like this:
- - -
Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1814794449)
unknown function (ip: 1814644310)
unknown function (ip: 1814680251)
unknown function (ip: 1812530838)
unknown function (ip: 1819022029)
unknown function (ip: 1819024448)
unknown function (ip: 1819024746)
unknown function (ip: 1814613991)
unknown function (ip: 1814617158)
unknown function (ip: 1811293047)
unknown function (ip: 1811259370)
unknown function (ip: 1811228604)
 at  (unknown line)
unknown function (ip: 14075376)
unknown function (ip: 1811450830)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c2b90d1 -- unknown function (ip: 181
4794449)
unknown function (ip: 1811215005)
Terminate batch job (Y/N)?
- - -

This is my julia config:
- - -
julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 3 entries:
  "Dates"  => v"0.3.2"
  "Compat" => v"0.2.7"
  "PyCall" => v"0.7.3"

julia> versioninfo()
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
- - -
Thanks, Gus

**Comment by stevengj** [comment]
Hmm, I can't replicate on my Mac with Julia 0.3 or 0.4.  What Python distro are you using?  (I generally recommend Anaconda.)

@tkelman, can you reproduce this?

**Comment by niugaust** [comment]
I reinstalled julia (0.3.4 this time) but now in the default folder C:\Users\xxuser.xxname\AppData\Local\Julia-0.3.4

This seems to help. I had julia installed in c:\julia

I am using python installed with the windows binary from python.org

**Comment by tkelman** [comment]
The folder name you install to shouldn't really matter (though spaces in the name can occasionally cause issues, try to avoid that if you can), but I'll put this down to one of the bugs we've fixed on release-0.3 unless you can reproduce it with the latest version. Little busy to try reproducing this right now.

**Comment by niugaust** [comment]
Hello,

This is weird:

If i have this in my bat file it seems to run fine:

for /L %%A in (0,1,1000) DO julia -e "println(strftime(time()));using PyCall;println(strftime(time()))"

However if i have

for /L %%A in (0,1,1000) DO julia pyc.jl

and in the pyc.jl

println(strftime(time()))
using PyCall
println(strftime(time()))

It hangs after a few iterations. If I ctrl+c i sometimes get this or similar:

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION
Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6c0d2893 --  at 0x6c71be74 -- unknown
 function (ip: 1819393652)
utf8proc_NFKC at C:\Users\service-catmwcf\AppData\Local\Julia-0.3.4\bin\libjulia
.dll (unknown line)

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0)

Not sure if this is actually the same as my original issue. 

I started from a clean VM with windows installed and nothing else. I installed julia and Pkg.add("PyCall). I didnt even install python. It seems it is not actually required for "using PyCall"

I then repeated the steps with another package, Gadfly, instead of PyCall and no issues for that one.

julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 3 entries:
  "Dates"  => v"0.3.2"
  "Compat" => v"0.2.9"
  "PyCall" => v"0.7.3"

julia> versioninfo()
Julia Version 0.3.4
Commit 3392026* (2014-12-26 10:42 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3


Thanks, Gus
