### ISSUE TITLE
Unable to use `pygments` via `PyCall`

### ISSUE THREAD

**Issue by dpsanders** [stevengj/PyCall.jl#115]
I am trying to use the Python `pygments` module for syntax highlighting. In Python we can do

    from pygments.lexers import JuliaLexer

but the apparently equivalent

    using PyCall
    @pyimport pygments.lexers as lexers
    lexers.JuliaLexer

gives the error

```
JuliaLexer not defined
while loading In[3], in expression starting on line 1
```

I had a look at the `pygments` package, and there seems to be some strange initialization going on in `lexers/__init__.py` that automagically instantiates the Lexer objects, or something like that, that means that the objects are not found by `PyCall`.

Is there any way round this problem?

**Comment by stevengj** [comment]
Try `lexers.pymember(:JuliaLexer)`

**Comment by dpsanders** [comment]
Great, thanks very much!
