### ISSUE TITLE
PyObject -> Array fails on julia 0.4

### ISSUE THREAD

**Issue by swt30** [stevengj/PyCall.jl#117]
I have the same problem as #99 with [this FITS file](http://fits.gsfc.nasa.gov/samples/WFPC2ASSNu5780205bx.fits) using `astropy.io.fits` on julia 0.4. It works fine on julia 0.3.

```jl
julia> using PyCall
julia> @pyimport astropy.io.fits as pyf
julia> fitsfile = pyf.open("data/fits-image.fits")
    1-element Array{Any,1}:
     PyObject <astropy.io.fits.hdu.image.PrimaryHDU object at 0x92512e4c>
julia> image = fitsfile[1]
    PyObject <astropy.io.fits.hdu.image.PrimaryHDU object at 0x92512e4c>
julia> pyimdata = image[:data]
```

At this stage pyimdata is an `Array{Float32, 2}` on julia 0.3 (perfect!) but a `PyObject array([[...]], dtype=float32)` on julia 0.4. Calling `convert(Matrix{Float32}, pyimdata)` gives exactly the same error as in #99:

```
ERROR: PyError (:PyFloat_AsDouble) <type 'exceptions.TypeError'>
TypeError('only length-1 arrays can be converted to Python scalars',)
...
```

v0.4 info:
```
Julia Version 0.4.0-dev+3307
Commit a387920* (2015-02-11 21:42 UTC)
Platform Info:
  System: Linux (i686-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
I can't reproduce.  Can you try a `Pkg.update()` to see if this was fixed recently?

**Comment by swt30** [comment]
Yeah, I can no longer reproduce it either. This seems to have been fixed somewhere along the line - but thanks for looking into it!
