### ISSUE TITLE
Python object construction not straightforward

### ISSUE THREAD

**Issue by ma-laforge** [stevengj/PyCall.jl#120]
After running a few tests, it appears there are 2 ways to construct an object.
Let us assume a python module was imported in Julia:
> @pyimport MyModule as mm

1) If your Python object is derived from "object", you get the nice call syntax:
> #Python:
> class MyObj1(object): ...
> #Julia:
> mm.MyObj1([constructor args...])

2) If your Python object is *not* derived from "object", the syntax is not as nice:
> #Python:
> class MyObj2(): ...
> #Julia:
> pycall(mm.MyObj2, PyObject, [constructor args...])

My experiments show the two constructor syntaxes *cannot* be interchanged.

Though a little confusing, this is not so bad.  It might be nice to have it mentioned in README.md.

Great module!

**Comment by stevengj** [comment]
This will go away in Julia 0.4 once I can make all PyObjects callable, I think (see #101).

**Comment by ma-laforge** [comment]
Sounds good to me.  I guess I will close the issue.  Thanks.
