### ISSUE TITLE
A note to pyenv users on Mac

### ISSUE THREAD

**Issue by randy3k** [stevengj/PyCall.jl#122]
I am on a Mac and using [pyenv](https://github.com/yyuu/pyenv) to manage my python versions. 

When I run PyCall on a specific python version, I got
```
ImportError: No module named site
````

I dug in the code and discovered that the python dynamic library was not detected correctly.
It turns out that one have to install python via `pyenv` with `--enable-framework` in order to have the essential file installed.

```
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.4.3
```

I just want to make a note here for future `pyenv` users

**Comment by stevengj** [comment]
What precisely does `--enable-framework` do?   Is PyCall not detecting the library, or is the library file that we need not installed?

**Comment by randy3k** [comment]
`--enable-framework` will create the dynamic library `lib/libpython3.4.dylib` which is necessary for `dlopen`.
see also https://github.com/yyuu/pyenv/issues/99

Without it, it installs only static library `lib/libpython3.4m.a`.
