### ISSUE TITLE
cannot import scipy.optimize 

### ISSUE THREAD

**Issue by epifanio** [stevengj/PyCall.jl#123]
I'm trying to follow the example notebook http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Help.ipynb but at the step : 

```
using PyCall
@pyimport scipy.optimize as so
```

I got this log : 

```
PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('cannot import name scimath',)
  File "/usr/lib64/python2.7/site-packages/scipy/__init__.py", line 70, in <module>
    from numpy import show_config as show_numpy_config
  File "/usr/lib64/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/lib64/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath

while loading In[10], in expression starting on line 372

 in pyerr_check at /home/epifanio/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /home/epifanio/.julia/v0.3/PyCall/src/PyCall.jl:91
```

The previous error is using python2, numpy, scipy and scimath are installed correctly.

However :
 
```
import scimath as emath
```

this module doesn't build on python 3
How to force julia to use python 3 ?

**Comment by epifanio** [comment]
seems it is a bug on my centos server :  https://github.com/JuliaLang/julia 
from ... https://github.com/stevengj/PyPlot.jl/issues/108
 i'll installe a recent julia from src and report back here

**Comment by stevengj** [comment]
Let me know if that fixes it for you.  You can force PyCall to use Python 3 by either setting the `PYTHON` environment variable to `python3` (assuming that is the name of your Python 3 executable) or by `using PyCall; pyinitialize("python3")`.  See the PyCall README file.

**Comment by stevengj** [comment]
Assuming that it works now...
