### ISSUE TITLE
Trying to make obj.o[] syntax work

### ISSUE THREAD

**Issue by bk322** [stevengj/PyCall.jl#126]
Hi, I'm trying to use matplotlib's OO interface, but can't use figure's method `add_subplot`:
```
#!/usr/bin/env julia

using PyCall
@pyimport matplotlib
matplotlib.use("pgf")
@pyimport matplotlib.pyplot as plt

x = linspace(0,2*pi,1000)
y = sin(3*x + 4*cos(2*x))

fig = plt.figure()
ax = fig.add_subplot(111) # gives error

l1, = ax.plot(x, y, "r-")
l2, = ax.plot(x, y*2, "g--")

ax.legend([l1, l2], [ur"$a$", ur"$b$"], loc=0)

ax.grid(True)

fig.tight_layout()

fig.savefig("test.png")
```
I also tried `fig.o[:add_subplot(111)]` but it doesn't work. Is it possible?

**Comment by stevengj** [comment]
Use `fig[:add_subplot](111)`.  See the README for PyCall — this is the biggest syntax difference from Python.

**Comment by bk322** [comment]
Thanks for a reply. But it gives `ERROR: `getindex` has no method matching getindex(::Ptr{PyObject_struct}, ::Symbol)`, whereas executing the same code in python works. What could it be?

**Comment by stevengj** [comment]
`fig[:add_subplot](111)`, not `fig.o[:add_subplot](111)`

**Comment by stevengj** [comment]
(See also the PyPlot package for a bit friendlier interface to matplotlib in Julia, supporting interactive plots.)

**Comment by bk322** [comment]
Thanks again for a reply. Now it mostly works, but legend: `ax[:legend]([l1, l2], ["$a$", "$b$"], loc=0)` gives `invalid interpolation syntax: """`. What could that be?

**Comment by bk322** [comment]
If one removes dollars: `ax[:legend]([l1, l2], ["a", "b"], loc=0)`, it gives `True not defined`.

**Comment by bk322** [comment]
The following works:
```julia
#!/usr/bin/env julia

using PyCall
@pyimport matplotlib
matplotlib.use("pgf")
@pyimport matplotlib.pyplot as plt

x = linspace(0,2*pi,1000)
y = sin(3*x + 4*cos(2*x))

fig = plt.figure()
ax = fig[:add_subplot](111)

l1, = ax[:plot](x, y, "r-")
l2, = ax[:plot](x, y*2, "g--")

ax[:legend]([l1, l2], ["\$a\$", "\$b\$"], loc=0)

ax[:grid](true)
fig[:tight_layout]()

fig[:savefig]("test.png")
```
Thank!

**Comment by stevengj** [comment]
You can also use `L"a", L"b"` if you use the [LaTeXStrings](https://github.com/stevengj/LaTeXStrings.jl) package, which makes it easier to type strings with LaTeX equations.  This is what PyPlot uses.
