### ISSUE TITLE
pyimport segmentation fault in virtualenv

### ISSUE THREAD

**Issue by multidis** [stevengj/PyCall.jl#127]
Activating virtualenv, then starting Julia. A python package (call it `pypkg`) is installed in virtualenv from source via `pip install -e git+https...` and resides in `src/` of virtualenv.

    using PyCall
    @pyimport pypkg

 **signal (11): Segmentation fault**
pthread_join at /lib/x86_64-linux-gnu/libpthread.so.0 (unknown line)
blas_thread_shutdown_ at /usr/lib/libblas.so.3 (unknown line)
__libc_fork at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_IO_proc_open at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
popen at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 735531670)
PyEval_EvalFrameEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalFrameEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalFrameEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalCodeEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalCode at /usr/lib/libpython2.7.so (unknown line)
PyImport_ExecCodeModuleEx at /usr/lib/libpython2.7.so (unknown line)
unknown function (ip: 736367470)
unknown function (ip: 736369356)
unknown function (ip: 736189889)
unknown function (ip: 736370911)
PyImport_ImportModuleLevel at /usr/lib/libpython2.7.so (unknown line)
unknown function (ip: 735313135)
PyObject_Call at /usr/lib/libpython2.7.so (unknown line)
PyEval_CallObjectWithKeywords at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalFrameEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalCodeEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalCode at /usr/lib/libpython2.7.so (unknown line)
PyImport_ExecCodeModuleEx at /usr/lib/libpython2.7.so (unknown line)
unknown function (ip: 736367470)
unknown function (ip: 736369356)
unknown function (ip: 736189759)
unknown function (ip: 736370980)
PyImport_ImportModuleLevel at /usr/lib/libpython2.7.so (unknown line)
unknown function (ip: 735313135)
PyObject_Call at /usr/lib/libpython2.7.so (unknown line)
PyEval_CallObjectWithKeywords at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalFrameEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalCodeEx at /usr/lib/libpython2.7.so (unknown line)
PyEval_EvalCode at /usr/lib/libpython2.7.so (unknown line)
PyImport_ExecCodeModuleEx at /usr/lib/libpython2.7.so (unknown line)
...

Running Julia Version 0.3.7 (2015-03-23 21:36 UTC) from Ubuntu 12.04 stable repository. NOTE: Just updated Julia version from 0.3.6 today, not sure but that update may have something to do with the error since in the past `@pyimport` worked for `pypkg` (although some required packages were updated so I can not be completely sure it was Julia update that broke things down).

Tried also including package `pypkg` source in the current dir (instead of virtualenv, keeping only prereq. in virtualenv) and doing `unshift!(PyCall.PyVector(PyCall.pyimport("sys")....`. Still the same segmentation fault. Everything works in a pure python shell from virtualenv.

**Comment by multidis** [comment]
UPDATE: Interestingly enough, the same steps work fine on another machine with the same Julia, Python, virtualenv, and Ubuntu versions. Quite puzzling: not sure what to start checking on the machine that gives the segmentation fault described above.

**Comment by proteasome** [comment]
a) since you updated to 0.3.7 from 0.3.6, suggest you try on 0.3.6.  even tho you got it 0.3.7 working on a different machine, something might still be broken in your updatecloser process.

if it works on 0.3.6 and fails on 0.3.7 on the same machine, you have somewhere to start doing diffs

b)  since you have seemingly identical versions running and failing.  check all the configuration files and environmental settings that get created by Julia, between the two versions running on the same machine.

c) check all your config and environments between the two machines.

d) run and log as verbose as you can  on working and failing versions of 0.3.7 and look for departure points.  you may actually not have updated cleanly.

e) reinstall 0.3.7 from scratch after as deep of a reboot as you can do.  some queue or flag somewhere may be trashed

f) good luck!

en


-----Original message-----

**Comment by multidis** [comment]
It starts to look like a virtualenv problem. When I run

    using PyCall
    @pyimport numpy

everything works NOT from virtualenv (numpy installed as Ubuntu 12.04 package).

Repeating the same from an activated virtualenv that has only python 2.7 and numpy (`pip install numpy`) returns

signal (11): Segmentation fault
pthread_join at /lib/x86_64-linux-gnu/libpthread.so.0 (unknown line)
blas_thread_shutdown_ at /usr/lib/libblas.so.3 (unknown line)
blas_shutdown at /usr/lib/libblas.so.3 (unknown line)
unknown function (ip: -2103445234)
unknown function (ip: -2126498383)
unknown function (ip: -2126498251)
unknown function (ip: -2119380018)
quit at client.jl:38
jlcall_quit_20841 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: -2119450580)
unknown function (ip: -2119455727)
unknown function (ip: -2119394232)
jl_f_top_eval at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
eval_user_input at REPL.jl:53
jlcall_eval_user_input_19963 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at task.jl:95
jl_handle_stack_switch at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_trampoline at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 4199453)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199509)
Segmentation fault (core dumped)

Where does it seem to be on a {python issue} ... {julia issue} scale?

**Comment by multidis** [comment]
Ended up upgrading to Ubuntu 14.04 and rebuilding everything I could (Python, Julia, BLAS libs etc.). Everything works now from virtualenv; closing the issue as too specific.

**Comment by proteasome** [comment]
sounds you diagnosed it properly:  a mismatch somewhere.  sometimes a clean rebuild on a stable rev is all you can do.

en

nathan kohn
enzyme@bu.edu
CS*mathematics:DATA+DNA+SLA+ASL+#
BU Metropolitan College
617 596 3626 cell/text 7x24
follow me @en_zyme
________________________________
