### ISSUE TITLE
GTK 3 (PyGObject) Example

### ISSUE THREAD

**Issue by niutech** [stevengj/PyCall.jl#132]
I want to play with a GUI in GTK3 via PyGObject, but I cannot show even a single window:
```julia
using PyCall
pygui_start(:gtk3)
@pyimport gi.repository.Gtk as Gtk
win = Gtk.Window()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```
It gives me `ERROR: LoadError: type PyObject has no field connect` in the latest Julia 0.4.
What is wrong here? Could you provide a working example of a GTK3 app? Thanks!

**Comment by stevengj** [comment]
See the PyCall documentation: the biggest difference from Python is that `foo.bar(...)` gets replaced by `foo[:bar](...)`, because Julia does not currently support `.` overloading (JuliaLang/julia#1974).

**Comment by stevengj** [comment]
The following works for me:
```jl
using PyCall
Gtk = pyimport("gi.repository.Gtk")
win = Gtk[:Window]()
win[:connect]("delete-event", Gtk["main_quit"])
win[:show_all]()
Gtk[:main]()
```

**Comment by niutech** [comment]
Still not working, I got an ERROR: MethodError: `call` has no method matching call(::PyCall.PyObject)
in `win[:show_all]()`

**Comment by stevengj** [comment]
Do `pycall(win["show_all"], PyAny)`.   See #101.

**Comment by niutech** [comment]
Thanks, now it works fine when using:
```Julia
pycall(win["show_all"], PyAny)
pycall(Gtk["main"], PyAny)
```
but why do I get the error when using `win[:show_all]()` and `Gtk[:main]()` in the latest Julia 0.4.0-dev+4559, PyCall.jl from the latest commit, GTK 3.10.8 and PyGObject 3.12.0 under Ubuntu 14.04 LTS?

**Comment by stevengj** [comment]
@niutech, maybe the latest Gtk is returning some special type for `win["show_all"]` and PyCall can't detect that it is a function and convert it to such?

In any case, this issue of the difficulty of determing which Python objects should be converted to Julia functions will go away once 0.4 is released and I implement #101 (so that all PyObjects will become callable).

**Comment by niutech** [comment]
Ok, thanks for the explanation.

**Comment by niutech** [comment]
One more thing, how to connect signals to the button, as in this example:
```Python
class Handler:
    def onDeleteWindow(self, *args):
        Gtk.main_quit(*args)
    def onButtonPressed(self, button):
        print("Hello World!")

builder = Gtk.Builder()
builder.add_from_file("builder_example.glade")
builder.connect_signals(Handler())
```
How to convert this code to Julia? Thanks in advance!

**Comment by niutech** [comment]
I simplified my example:
```Julia
function on_button_clicked()
    println("Hello World")
end
button = Gtk[:Button](label="Click Here")
button[:connect]("clicked", on_button_clicked)
```
But upon running I get this error:
`RuntimeError: Julia exception: MethodError(on_button_clicked,(PyObject <Button object at 0xb0fcf9dc (GtkButton at 0xd93f420)>,))`
So how can I attach listeners to events in Julia?

**Comment by stevengj** [comment]
`MethodError` means that something is trying to call `on_button_clicked` with arguments different from the method signature you defined.   Are you sure that it doesn't accept arguments?  Try:
```
function on_button_clicked(args...)
    println("Hello World args = ", args)
end
```

**Comment by niutech** [comment]
It works! The output is:
`Hello World args = (PyObject <Button object at 0xb0d6f644 (GtkButton at 0xd2ff118)>,)`
Thank you very much for your support!

**Comment by stevengj** [comment]
presumably the right signature is `function on_button_clicked(button::PyObject)`.
