### ISSUE TITLE
Can not import class from python module

### ISSUE THREAD

**Issue by akaFalsh** [stevengj/PyCall.jl#136]
Dear collegues,

I have a python module that consists of several classes, which are actually a swig objects around c++. I had imported classes successfully, but when I am trying to call a method that was implemented in parent class, I obrain error:
"ERROR: type PyObject has no field getValueFunction()"

example:
```
using PyCall
@pyimport mypythonmodule
myclass =  mypythonmodule.pymember("myclass")
myvar = myclass[:function](inputvalue)
myvalue  = myvar.getValueFunction()
```

Best regards,
Vladislav

**Comment by stevengj** [comment]
I assume you figured out that the syntax is `myvar[:getValueFunction]()`
