### ISSUE TITLE
Results of subtypes of `list`, returns Array, rather than PyObject

### ISSUE THREAD

**Issue by oxinabox** [stevengj/PyCall.jl#139]
Consider the example python (in `example.py`)

```
class CustomList(list):
    def twice_len(self):
        return 2*len(self)


def get_c_list():
    return CustomList(["foo","bar"])
```

If I call in from julia:

```
using PyCall
unshift!(PyVector(pyimport("sys")["path"]), "");
@pyimport example
xs=example.get_c_list()
```

Then xs is not of type PyObject

````
IN[2]>xs
OUT[2]:> 2-element Array{Any,1}:
 "foo"
 "bar"
````

and its special method is not available:

```
IN[3]> xs.twice_len()
OUT[3]> type Array has no field twice_len
while loading In[3], in expression starting on line 1
```

This is a MWE.
It is a more serious issue in the python [NLTK](http://www.nltk.org/), which extends list often, in significant ways (Including using it to implement Trees).

**Comment by stevengj** [comment]
You can always inhibit conversion to a `Array` by using `pycall` to specify the desired return type.  e.g. `example = pyimport("example")` followed by `pycall(example["c_list"], PyVector)`.

There is a tension here between automatically converting Python objects to corresponding native Julia types, which are convenient for subsequent use in Julia, vs. leaving them as something closer to the native Python type, which is more convenient for subsequent use in Python.  Manual intervention (to specify the desired type) is likely to always be required in some cases if we guess wrong.

(Do you have a suggestion for how to pick a better default?)

**Comment by oxinabox** [comment]
Thanks. 
I worked that out just as you were posting this.
Now I have a new issue of what types Iterators/generators return, when Iterated in Julia.
I will again construct a MWE with my new knowledge and create another issue if I can't work it out.
