### ISSUE TITLE
Any way to run elevated python code?

### ISSUE THREAD

**Issue by amellnik** [stevengj/PyCall.jl#145]
I'm trying to use [mraa](https://github.com/intel-iot-devkit/mraa) on an intel edison through PyCall.  I need to run the equivalent python program as root in order to use the gpio.  Is there any way to run the python code elevated?

**Comment by stevengj** [comment]
The Python code in PyCall is executing in the same process as the Julia code, so if you want to run the Python code as root then Julia needs to be running as root also.

**Comment by amellnik** [comment]
Huh, I could have sworn that's what I tried, but I'll double-check tonight.
