### ISSUE TITLE
PyCall hangs when too many Python warnings are raised

### ISSUE THREAD

**Issue by oxinabox** [stevengj/PyCall.jl#149]
I am attempting to use GMMHMMs, from [hmmlearn](https://github.com/hmmlearn/hmmlearn)
They work fine in python.
The GaussianHMMs work fine with pycall (in julia).

But the GMMHMMs do not.
They just seem to hang.
No cpu is being used by python or julia while it is hanging.
(Checked using `top`)

MWE (the data might not exactly fit a GMMHMM, but that doesn't matter as to if the model should exectute on it -- it will just to badly)
Setup: Runs fine:

```
using PyCall
@pyimport hmmlearn.hmm as hl_hmm
function get_sample_data_run(length)
    xs = zeros(2,length)
    xs[:,1] = randn(2) + (randbool() ? [1,1]: [0,0])
    for ii in 2:length
        xs[:,ii] = -1*xs[:,ii-1] + randn(2) + (randbool() ? randbool() ?  [1,1]:[-1,-1]: [0,0])
    end
    xs
end
xs_all = [get_sample_data_run(rand(3:10))' for _ in 1:100]
hmm = hl_hmm.GMMHMM(n_components=3, n_mix=3, covariance_type="full", n_iter=2)

```

Line that hangs:

```
pycall(hmm["fit"],PyObject, xs_all) 
```

It also hangs when I used `hmm[:fit](xs_all)`

-------

hmmlearn.__version__=0.1.1
PyCall 0.8.1

Julia Version 0.3.9-pre+12
Commit 66f081d (2015-05-09 08:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by oxinabox** [comment]
I have a theory, 
that this is related to large amount of warnings being thrown.
Because if I cut the  number of samples in `xs_all`,
from 100, down to 2.
It works, but throws 18 warnings.
If i make the number of samples 3, it throws 23 warnings.

If I make it up to something big, eg 100,
It hangs.

So my theory is the Buffer that warnings go into gets full and it stops working.

**Comment by oxinabox** [comment]
Further more if I first run:

```
@pyimport warnings
warnings.filterwarnings("ignore")
```

It works fine.
If you can't reproduce, I could throw together a MWE.

**Comment by stevengj** [comment]
Possibly this is a dup of #243 and https://github.com/JuliaLang/julia#8789?  In IJulia, due to inherent limitations of OS kernel buffers, writing too much to a IO buffer from the same thread that is reading it will inevitably deadlock.

It's not clear if it is possible to fix this.

(Note that the IPython kernel punts entirely on the issue; my recollection is that it can't capture stdio by external C libraries.)

**Comment by stevengj** [comment]
Closing as a dup.
