### ISSUE TITLE
Accessing the PyObject

### ISSUE THREAD

**Issue by kaarthiksundar** [stevengj/PyCall.jl#151]
I am a new julia user and I am having difficulty understanding how to access the contents of  PyObject that is returned from a python function call. 

julia> using PyCall
julia> @pyimport networkx as nx
julia> G = nx.erdos_renyi_graph(10,0.1,directed=true)
PyObject <networkx.classes.digraph.DiGraph object at 0x7f24b6a5f450>
julia> scc = nx.strongly_connected_components(G)
PyObject <generator object strongly_connected_components at 0x7f24b2aeeeb0>

Now, how do I get the connected components. The documentation lacks examples and it would be great if some complicated examples are added. Also, any help with the above issue is appreciated.

**Comment by jakebolewski** [comment]
The Python

```python
scc.some_method(arg1, arg2)
```
gets translated into the following Julia code

```julia
scc[:some_method](arg1, arg2)
```

**Comment by kaarthiksundar** [comment]
scc is a generator expression in python. I have to iterate over it to get the lists. In python to get the components I would do 

for i in scc:
    print i

This would give me the lists. If I do an equivalent for loop in julia, it does not print anything.

**Comment by jakebolewski** [comment]
This works for me on the latest PyCall `master` branch (`Pkg.checkout("PyCall", "master")`).  You might need up update your version of PyCall?

```julia
julia> scc = nx.strongly_connected_components(G)
PyObject <generator object strongly_connected_components at 0x31fcf8b88>

julia> for s in scc
       @show s
       end
s = Any[5]
s = Any[2,6,4]
s = Any[7]
s = Any[0]
s = Any[1]
s = Any[3]
s = Any[8]
s = Any[9]
```

**Comment by kaarthiksundar** [comment]
How can you cast them into julia native data type to do further manipulations?

**Comment by jakebolewski** [comment]
Cast what? As you see the variable `s` is an Julia `Any` Array (conversion type from a Python list).

**Comment by stevengj** [comment]
Ideally, we should implement conversion of generators into Julia iterators; converting to an explicit Array is problematic for generators that produce huge (possibly unbounded) sequences.

**Comment by stevengj** [comment]
Wow, I totally forgot that I implemented this.   Yes, Julia iteration over `PyObject`s corresponding to Python generator objects is already implemented and has been for some time.  So, you can loop over a generator with `for`, convert it into an array with `collect`, and in general do whatever you might want to do with a Julia iterator.
