### ISSUE TITLE
No-copy wrapper for julia functions

### ISSUE THREAD

**Issue by bermanmaxim** [stevengj/PyCall.jl#159]
Currently, when I execute the following snippet

```
using PyCall;
a = [0]
function increment(a)
    a[1] += 1
end
pyeval("increment(a)", increment=increment, a=a)
```

the array a is copied at some point, since the value of the original array does not change. Using a PyArray as array `a` does not change this.

I am not sure where this copy happens during the wrapping of `increment`, but I would be interested to know if there was a way to avoid doing a copy of a. (I am trying to use Julia functions as callbacks in a Python code to benefit from Julia's speed...)

**Comment by stevengj** [comment]
The issue is that when the Python wrapper function is called, it first converts the argument from Python back to Julia before passing it to the Julia `increment`.   Right now, PyCall defaults to making a copy when it converts arrays from Python to Julia.

I can't think of a way to work around this without modifying the PyCall source code.

**Comment by bermanmaxim** [comment]
Hello, thanks; I tried removing the conversions `convert(PyAny, args)` in `jl_Function_call` from `callback.jl` (providing `args` directly to the julia called function).

I ended up with this code: https://gist.github.com/bermanmaxim/65a568b6db9093d92f3d

I know that my custom wrapper is used (it prints `custom wrapper used`), and still there seem to be a copy somewhere...

I wonder if it happens in `args = PyObject(args_)` ...

**Comment by stevengj** [comment]
No, the Julia->Python conversion in `PyObject` should default to no-copy conversion, assuming you have NumPy.

**Comment by stevengj** [comment]
Grr, it looks like that broke at some point:
```
julia> A = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> o = PyObject(A)
PyObject [1, 2, 3]

julia> A[1] = 17
17

julia> o
PyObject [1, 2, 3]
```

**Comment by bermanmaxim** [comment]
For me, on `PyCall` master, this no-copy does work ;)

```
julia> A = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> o = PyObject(A)
PyObject array([1, 2, 3])

julia> A[1] = 17
17

julia> o
PyObject array([17,  2,  3])
```

But in my particular problem, I suspect a copy happens because in `jl_Function_call` the step
`args = PyObject(args_)`
does not convert a python array to a `PyObject`, but a `Ptr{PyCall.PyObject_struct}` to a `PyObject`... And I have not understood how this conversion happens, but it seems to involve a copy of the arrays contained in the arguments...

**Comment by bermanmaxim** [comment]
Yes! I finally got it. The copy is happening because of the splat operator in `callback.jl` ([L40](https://github.com/stevengj/PyCall.jl/blob/0f53e5113184556085f7980c26020316b0793e38/src/callback.jl#L40))
```
ret = PyObject(f(convert(PyAny, args)...; kwargs...))
```
removing the conversion:
```
ret = PyObject(f(args...; kwargs...))
```
does not help, because the splatting `...` ultimately calls `next` as defined in `conversions.jl`:[874](https://github.com/stevengj/PyCall.jl/blob/0f53e5113184556085f7980c26020316b0793e38/src/conversions.jl#L874), with a conversion to `PyAny`.

Replacing the conversion to `PyAny` to a conversion to `PyArray` in my particular example ensure preserving the original `PyArray`. I will update my gist accordingly, since this might interest other people...

**Comment by bermanmaxim** [comment]
Ok, so [here is my gist](https://gist.github.com/bermanmaxim/65a568b6db9093d92f3d) with a no-copy wrapper around a Julia function.

I don't know if there is a way to suppress the two "method definition overwritten" warnings.

I think this issue can be closed, it would be nice to have an easier way to do this though. It would be nice to have an array type that is not copied when converted between Python and Julia, even when a conversion to `PyAny` is asked for.
