### ISSUE TITLE
Segmentation fault when iterating over non-iterable PyObject

### ISSUE THREAD

**Issue by bermanmaxim** [stevengj/PyCall.jl#160]
Maybe a check for a PyObject to be iterable should be added before using it as a container ?

Example
```
julia> using PyCall

julia> a = PyObject()
PyObject NULL

julia> [a...]

signal (11): Segmentation fault
PyObject_GetIter at /usr/lib/x86_64-linux-gnu/libpython2.7.so (unknown line)
start at /.../.julia/v0.4/PyCall/src/conversions.jl:81
```

**Comment by stevengj** [comment]
It already checks if the object is iterable.

The issue is that `PyObject()` just returns a NULL object pointer, not a valid object, and it is not supposed to be called from user code.  I will remove this function and replace it with something non-exported.
