### ISSUE TITLE
Warning in Julia 0.4

### ISSUE THREAD

**Issue by juliohm** [stevengj/PyCall.jl#162]
```julia
using PyCall
```
>Warning: New definition 
    call(Type{PyCall.PyDict}, Base.Associative{#K<:Any, Any}) at /home/julio/.julia/v0.4/PyCall/src/conversions.jl:464
is ambiguous with: 
    call(Type{PyCall.PyDict}, Base.Associative{Any, #V<:Any}) at /home/julio/.julia/v0.4/PyCall/src/conversions.jl:463.
To fix, define 
    call(Type{PyCall.PyDict}, Base.Associative{Any, Any})
before the new definition.

**Comment by stevengj** [comment]
Yes, looks this just appeared in the last 24 hours or so; I'm not sure what change in `Base` prompted this, but it should be easy to fix.

**Comment by stevengj** [comment]
That's weird, I saw it this morning on one computer, but I just pulled the latest `julia` and built it, and the warning seems to have gone away.  @juliohm, can you still reproduce if you update `julia`?

**Comment by juliohm** [comment]
Hi Steven,

Will update Julia and retry today.

Thanks.
