### ISSUE TITLE
PyCall fails with matplotlib.pyplot on Mac OSX with Anaconda?

### ISSUE THREAD

**Issue by pmota0** [stevengj/PyCall.jl#163]
With PATH=/Users/pmota/anaconda/bin:<etc> on my Mac,
@pyimport matplotlib.pyplot as plt
gives
signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6

With PATH=/Users/pmota/Library/Enthought/Canopy_64bit/User/bin:<etc>
@pyimport matplotlib.pyplot as plt
gives
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named matplotlib.pyplot',)

 in pyerr_check at /Users/pmota/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /Users/pmota/.julia/v0.3/PyCall/src/PyCall.jl:91
which is strange because the modules exist in Canopy.

The system was working fine, I think that things went wrong with a recent update of Anaconda...

**Comment by stevengj** [comment]
Canopy won't work (#42).

**Comment by stevengj** [comment]
I just tried updating to the latest Anaconda on my laptop (OSX 10.10.3) and it works fine.  What version of Julia are you using?

Maybe by having both Anaconda and Canopy on your system you have messed up the paths somehow so that the two are fighting with each other?

**Comment by pmota0** [comment]
I sorted out what the problem was: I have a series of libraries that I recently installed into "/Users/pmota/local/lib" (my username is pmota) and exported DYLD_LIBRARY_PATH=/Users/pmota/local/lib in my .profile file. One of the libraries is openblas, and it was conflicting with Julia's openblas lib. So, instead of calling julia directly I created a small shell script:

#!/bin/sh
export DYLD_LIBRARY_PATH=/Applications/Juno.app/Contents/Resources/app/julia/lib/julia:$DYLD_LIBRARY_PATH"
exec "/Applications/Juno.app/Contents/Resources/app/julia/bin/julia" "$@"

and then things seemed to work fine until I called PyPlot. However, changing the script to
#!/bin/sh
unset DYLD_LIBRARY_PATH
exec "/Applications/Juno.app/Contents/Resources/app/julia/bin/julia" "$@"

works all the time. Don't ask me why...

**Comment by pmota0** [comment]
Forgot to mention that PyPlot is awesome.

**Comment by stevengj** [comment]
Great, thanks!

**Comment by stevengj** [comment]
(Probably, both NumPy and Julia are using OpenBLAS, and they are stepping on each others' toes.)
