### ISSUE TITLE
PyCall only loads during the session in which it's built

### ISSUE THREAD

**Issue by swt30** [stevengj/PyCall.jl#173]
See https://github.com/stevengj/PyCall.jl/issues/167#issuecomment-124825724

deps.jl contains:

```
const python = "python"
const libpython = "libpython3.4m"
const pyprogramname = wstring("/home/scott/.virtualenvs/py3/bin/python")
const pyversion_build = v"3.4.3"

const PYTHONHOME = "/home/scott/.virtualenvs/py3:/home/scott/.virtualenvs/py3"

const PyUnicode_AsUTF8String = :PyUnicode_AsUTF8String
const PyUnicode_DecodeUTF8 = :PyUnicode_DecodeUTF8

const PyString_FromString = :PyBytes_FromString
const PyString_AsString = :PyBytes_AsString
const PyString_Size = :PyBytes_Size
const PyString_Type = :PyBytes_Type
const PyInt_Type = :PyLong_Type
const PyInt_FromSize_t = :PyLong_FromSize_t
const PyInt_FromSsize_t = :PyLong_FromSsize_t
const PyInt_AsSsize_t = :PyLong_AsSsize_t

const Py_hash_t = Int64

const pyunicode_literals = true
```

**Comment by swt30** [comment]
Other info that may be useful:
* virtualenvwrapper doesn't appear to use `PYTHONHOME`, but `ENV["PYTHONHOME"]` gets set to the above value upon `Pkg.build("PyCall")`, at which point everything works fine
* however, `ENV["PYTHONHOME"]` doesn't exist after restarting Julia and triggering the failure by `using PyCall`

**Comment by stevengj** [comment]
@swt30, `ENV["PYTHONHOME"]` is currently only set (in `PyCall.__init__`) while initializing Python, so it wouldn't be set after `using PyCall` completes.

I should also really unset it and other environment variables after `Pkg.build("PyCall")`, in order to avoid triggering #91.

It looks like the right thing is for me not to use the environment variable at all, but rather to use `Py_SetPythonHome`.

**Comment by stevengj** [comment]
Okay, I've pushed a patch that uses `Py_SetPythonHome`, can you try it and see if it fixes your problem?

**Comment by swt30** [comment]
Not yet, but I'm reinstalling the virtual environment with an updated version of virtualenvwrapper to see if that changes things.

**Comment by swt30** [comment]
No luck, I'm afraid! Same behaviour as before.

**Comment by stevengj** [comment]
Does setting `ENV["PYTHONHOME"]` manually (see the value in PyCall/deps/deps.jl) work?  I'm confused.

**Comment by swt30** [comment]
Still no, unfortunately. The plot just thickened:

```julia
julia> using PyCall
WARNING: error initializing module PyCall:
ReadOnlyMemoryError()
```

This is in the same place, using a Python 2 virtual environment instead of Python 3. I don't have enough debugging skill to look much more deeply into where the error is coming from, but I'm happy to try any other suggestions to figure out what's something screwed up with my virtual environment.

**Comment by swt30** [comment]
For some reason, I am now getting only the ReadOnlyMemoryError with any Python, whether it's the system version or either virtual environment. Still in the same place after the session restart. I'm confused too.

**Comment by swt30** [comment]
Rebuilt Julia and now the error is back to the first one: `cglobal: could not find symbol PyCObject_FromVoidPtr in library libpython3.4m`. I'm reverting to an earlier version of PyCall for now, but do let me know if you have any steps you want me to try.

**Comment by stevengj** [comment]
@swt30, does the error persist if you manually set the `PYTHONHOME` environment variable?

**Comment by swt30** [comment]
It does.

**Comment by swt30** [comment]
I'm on Julia master; would it be worthwhile bisecting on either Julia or PyCall to see if this behaviour started with a specific commit?

**Comment by swt30** [comment]
Can verify that the behaviour is still around for me on v0.3.11, but not on another machine. I suppose something strange is going on with virtualenvwrapper. I'll see what happens if I disable it.

**Comment by stevengj** [comment]
That is so bizarre.  `Py_SetPythonHome` is supposed to be the preferred replacement for setting `PYTHONHOME` (which can screw up subprocesses), and the [source code of Python](https://github.com/python/cpython/blob/dafb2a203aae603257386fc6951c882a0d1e7ab8/Python/pylifecycle.c#L856-L878) (which hasn't changed much in this part since Python 2.7, except for the change from `char*` to `wchar_t*`) only reads 'PYTHONHOME' from `Py_GetPythonHome`, which always prefers the value set by `SetPythonHome`.

**Comment by swt30** [comment]
No change upon deactivating virtualenvwrapper. What on earth is going on with my system!?

**Comment by swt30** [comment]
As of https://github.com/stevengj/PyCall.jl/commit/493b3f00e8c2849d0620a6d6bb1b437453a81257, this is fixed in in my Python 2.7. The error still persists on Python 3.4. It's apparently coming from [line 72 in pyinit.jl](https://github.com/stevengj/PyCall.jl/blob/03e1f9b770b7f16e38c190180bd2fa0868ecc044/src/pyinit.jl#L72).

**Comment by swt30** [comment]
PyCObject was [deprecated in Python 2.7](https://docs.python.org/2/c-api/cobject.html) and removed somewhere in 3.x. So the fallback to CObject at [pyinit line 74](https://github.com/stevengj/PyCall.jl/blob/493b3f00e8c2849d0620a6d6bb1b437453a81257/src/pyinit.jl#L74) is failing. Do we need the new [PyCapsule API](https://docs.python.org/2/c-api/capsule.html#capsules) here instead?

**Comment by swt30** [comment]
... but then it still comes back to the fact that ctypes is failing to load. It's just that python 2.7 allows the fallback to PyCObject, while 3.4 doesn't. I think this is the same as #178. Closing in favour of that.

```
julia> using PyCall # with python 2.7
julia> pyimport("ctypes")
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so: undefined symbol: PyFloat_Type',)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array

 in pyimport at /home/scott/.julia/v0.4/PyCall/src/PyCall.jl:81

julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: PyCall is using python (Python 2.7.9) at /usr/bin/python, libpython = libpython2.7

julia> pyimport("ctypes")
PyObject <module 'ctypes' from '/usr/lib/python2.7/ctypes/__init__.pyc'>
```

**Comment by swt30** [comment]
for reference, [this issue on another project](https://github.com/potentialventures/cocotb/issues/146) notes a similar problem using Python's C API on Ubuntu, relating to symbol resolution on library load. They end up putting in another `dlopen` call before initing Python as well, which is the workaround I'm currently using.
