### ISSUE TITLE
Unable to use PyCall in Julia 3.10 on a Mac running Mac OS 10.4.4

### ISSUE THREAD

**Issue by ahausknecht** [stevengj/PyCall.jl#174]
I'm attempting to use Juilia 3.10 0n on a 2011 Mac Book Pro running Mac OS 10.4.4  with 16 GB of ram:
Here is the error message:

julia> using PyCall
ERROR: could not open file /Users/ahausknecht/.julia/v0.3/PyCall/src/../deps/deps.jl
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.10.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/ahausknecht/.julia/v0.3/PyCall/src/PyCall.jl, in expression starting on line 33

**Comment by stevengj** [comment]
You need to run `Pkg.build("PyCall")`

**Comment by tkelman** [comment]
ref #172
