### ISSUE TITLE
master breaks PyPlot

### ISSUE THREAD

**Issue by yuyichao** [stevengj/PyCall.jl#176]
I checked out the PyCall master today and got the following error when importing PyPlot

```julia
julia> using PyPlot
/usr/lib/python3.4/site-packages/matplotlib/__init__.py:1318: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
WARNING: error initializing module PyPlot:
PyCall.PyError(msg=":PyImport_ImportModule", T=PyCall.PyObject(o=0x00007ffdda4be380), val=PyCall.PyObject(o=0x00007ffdcc2c6c18), traceback=PyCall.PyObject(o=0x00007ffdcc043448))
```

Haven't investigate further but downgrading to 0.8.2 release fixes the issue.

**Comment by stevengj** [comment]
Works for me using the master of PyCall and PyPlot.

**Comment by yuyichao** [comment]
Maybe python2 vs python3?

**Comment by stevengj** [comment]
What system are you on, and what backend is matplotlib using?

**Comment by yuyichao** [comment]
ArchLinux x64. Python `3.4.3`. Matplotlib `1.4.3`,

```
% cat ~/.config/matplotlib/matplotlibrc
backend: Qt4Agg
```

**Comment by yuyichao** [comment]
And julia master

```julia
julia> versioninfo()
Julia Version 0.4.0-dev+6350
Commit 9b14a7c* (2015-07-29 10:26 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.6.1
```

**Comment by stevengj** [comment]
Could this be #177?

**Comment by yuyichao** [comment]
Not really the same (although could be related). #177 is happening on the released version while I only see this on master.

**Comment by stevengj** [comment]
You might try a `Pkg.update()` again to see if has been fixed by the recent PyCall updates.

**Comment by yuyichao** [comment]
It was broken sometime last week but seems to be fine now. Anyway, the original issue has been solved a long time ago (since it was working for sometime last month...)
