### ISSUE TITLE
pycall test failed latest Julia master

### ISSUE THREAD

**Issue by StephenVavasis** [stevengj/PyCall.jl#180]
I am trying to use PyPlot (for the first time), but it is not working:

```julia
julia> plot(x,y,color="red", linewidth=2.0, linestyle="--")
ERROR: UndefVarError: pltm not defined
 in plot at c:\Users\vavasis\Documents\.julia\v0.4\PyPlot\src\PyPlot.jl:368
```

I decided to first check if PyCall is working:

```julia
julia> Pkg.test("PyCall")
INFO: Testing PyCall
WARNING: could not import Base.help into PyCall
ERROR: LoadError: test failed: roundtripeq(Array,[1,2,3,4])
 in expression: roundtripeq(Array,[1,2,3,4])
 in error at error.jl:21
while loading c:\Users\vavasis\Documents\.julia\v0.4\PyCall\test\runtests.jl, in
 expression starting on line 169
===============================[ ERROR: PyCall ]================================
```

so I guess I'd better figure out what is wrong with PyCall before I worry about PyPlot.  My Julia version is the latest master:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6916 (2015-08-23 18:41 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f8c1986 (0 days old master)
|__/                   |  x86_64-w64-mingw32
```

and my packages are as follows:

```

julia> Pkg.status()
5 required packages:
 - Compat                        0.6.0
 - DataStructures                0.3.12-            SC_new_constructors
 - ImmutableArrays               0.0.10
 - NumericExtensions             0.6.2+             master
 - PyPlot                        1.5.3
12 additional packages:
 - ArrayViews                    0.6.3
 - Color                         0.4.7
 - Dates                         0.4.4
 - Docile                        0.5.16
 - FixedPointNumbers             0.0.10
 - Graphics                      0.1.1
 - LaTeXStrings                  0.1.4
 - Modifyfield                   0.0.0-             master (unregistered)
 - NumericFuns                   0.2.3
 - PyCall                        0.8.2
 - Unroll                        0.0.0-             master (unregistered)
 - microcoverage                 0.0.0-             master (unregistered)
```

**Comment by tbreloff** [comment]
I am having issues as well:
```
[tom@tomoffice ~]$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6930 (2015-08-24 09:35 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 40d2035 (0 days old master)
|__/                   |  x86_64-redhat-linux

julia> using PyCall
INFO: Precompiling module PyCall...
ERROR: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('/usr/lib64/python2.7/lib-dynload/operator.so: undefined symbol: _Py_ZeroStruct',)

 in pyimport at /home/tom/.julia/v0.4/PyCall/src/PyCall.jl:81
 in __init__ at /home/tom/.julia/v0.4/PyCall/src/pyinit.jl:44
 in _require_from_serialized at loading.jl:84
 in require at ./loading.jl:214SYSTEM: show(lasterr) caused an error

julia> Pkg.status("PyCall")
 - PyCall                        0.8.2+             master
```

**Comment by tbreloff** [comment]
I'm guessing that precompilation of PyCall has brought this Red Hat bug to the surface for me: https://bugzilla.redhat.com/show_bug.cgi?id=874874.  Is there a way for me to turn off precompilation for PyCall?  I tried commenting out the `VERSION >= v"0.4.0-dev+6521" && __precompile__()` line but that didn't work.

**Comment by tbreloff** [comment]
For anyone that may be in the same boat, it seems I fixed it like this:
```
[tom@tomoffice ~]$ export LD_PRELOAD=/usr/lib64/libpython2.7.so.1.0
[tom@tomoffice ~]$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6930 (2015-08-24 09:35 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 40d2035 (0 days old master)
|__/                   |  x86_64-redhat-linux

julia> using PyCall

julia> 
```

**Comment by stevengj** [comment]
I think @StephenVavasis may be hitting a separate issue, where the tests are failing in Python 3.

**Comment by StephenVavasis** [comment]
For my application I need to use Julia 0.4, but I'm happy to use any version of Python/PyCall/Pyplot that is known to be working.

**Comment by stevengj** [comment]
@StephenVavasis, can you try with Python 2.x?   This is what ships by default with Anaconda, for example.

**Comment by StephenVavasis** [comment]
Steven,

Here is the update.  First, I upgraded Julia to 0.4.0-rc1.  Next, I downloaded Anaconda for Windows 64.  Then I started Julia and set the environment variable.  Then I installed PyCall.jl and PyPlot.jl.  The installation of PyCall.jl seemed to go OK, but PyPlot.jl gave an error message.  See below.  

The strange thing about this error message is that it refers to an old python installation (c:\Program Files (x86)\Python27\..), not Anaconda.  

The invocation of the wrong python installation seems to be an issue with PyCall.jl rather than PyPlot.jl, because PyCall.pyimport("matplotlib") gave me the same error message (about requiring dateutil) and the same wrong Python installation.  By the way, running matplotlib from within Anaconda (i.e., invoking matplotlib from the python shell instead of from Julia) seems to work fine, and dateutil is installed in Anaconda.

Thanks,
Steve


julia> ENV["PYTHON"] = "c:\\Anaconda\\python.exe"
"c:\\Anaconda\\python.exe"

julia> Pkg.add("PyCall")
INFO: Installing Dates v0.4.4
INFO: Installing PyCall v0.8.2
INFO: Package database updated

julia> Pkg.build("PyCall")

julia> Pkg.test("PyCall")
INFO: Testing PyCall
WARNING: could not import Base.help into PyCall
INFO: PyCall tests passed

julia> Pkg.add("PyPlot")
INFO: Installing ColorTypes v0.1.4
INFO: Installing Colors v0.5.3
INFO: Installing Docile v0.5.18
INFO: Installing FixedPointNumbers v0.0.10
INFO: Installing LaTeXStrings v0.1.4
INFO: Installing PyPlot v2.0.1
INFO: Installing Reexport v0.0.3
INFO: Package database updated

julia> Pkg.build("PyPlot")

julia> using PyPlot
WARNING: could not import Base.help into PyCall
ERROR: LoadError: InitError: Failed to pyimport("matplotlib"): PyPlot will not w
ork until you have a functioning matplotlib module.  PyError (:PyImport_ImportMo
dule) <type 'exceptions.ImportError'>
ImportError(u'matplotlib requires dateutil',)
  File "C:\Program Files (x86)\Python27\lib\site-packages\matplotlib\__init__.py
", line 116, in <module>
    raise ImportError("matplotlib requires dateutil")

 in __init__ at c:\Users\vavasis\Documents\.julia\v0.4\PyPlot\src\PyPlot.jl:232
 in include at boot.jl:260
 in include_from_node1 at loading.jl:271
 in require at loading.jl:210
during initialization of module PyPlot
while loading c:\Users\vavasis\Documents\.julia\v0.4\PyPlot\src\PyPlot.jl, in ex
pression starting on line 653

**Comment by StephenVavasis** [comment]
Just as a further data point, i tried installing the latest PyCall master in 0.4.0-rc1, and I got a strange error from the testing.  Apparently an array is getting converted to an array-of-arrays.  See below.

```
julia> ENV["PYTHON"] = "c:\\Anaconda\\python.exe"
"c:\\Anaconda\\python.exe"

julia> Pkg.add("PyCall")
INFO: Installing Dates v0.4.4
INFO: Installing PyCall v0.8.2
INFO: Package database updated
INFO: METADATA is out-of-date - you may not have the latest version of PyCall
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> Pkg.checkout("PyCall")
INFO: Checking out PyCall master...
INFO: Pulling PyCall latest master...
INFO: No packages to install, update or remove

julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: PyCall is using c:\Anaconda\python.exe (Python 2.7.10) at c:\Anaconda\pyth
on.exe, libpython = c:\Anaconda\python27.dll

julia> Pkg.test("PyCall")
INFO: Testing PyCall
INFO: Recompiling stale cache file c:\Users\vavasis\Documents\.julia\lib\v0.4\Py
Call.ji for module PyCall.
ERROR: LoadError: test failed: roundtripeq(Array,[1,2,3,4])
 in expression: roundtripeq(Array,[1,2,3,4])
 in error at error.jl:21
while loading c:\Users\vavasis\Documents\.julia\v0.4\PyCall\test\runtests.jl, in
 expression starting on line 169
===============================[ ERROR: PyCall ]================================


failed process: Process(`'C:\Users\vavasis\AppData\Local\Julia-0.4.0-rc1\bin\jul
ia' --check-bounds=yes --code-coverage=none --color=yes 'c:\Users\vavasis\Docume
nts\.julia\v0.4\PyCall\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

ERROR: PyCall had test errors
 in error at error.jl:21
julia> using PyCall

julia> convert(Array, PyObject([1,2,3,4]))
4-element Array{Any,1}:
 0-dimensional Array{Int64,0}:
1
 0-dimensional Array{Int64,0}:
2
 0-dimensional Array{Int64,0}:
3
 0-dimensional Array{Int64,0}:
4

julia>
```

**Comment by stevengj** [comment]
@StephenVavasis, I think this should be fixed by 9304bbc5fe6fa00137e1949f104acfc86bedb107, can you try again?

**Comment by StephenVavasis** [comment]
Yes, PyCall and PyPlot both appear to be working now.  Here is the configuration that is working for me:

Windows 8.1 64-bit

Julia 0.4.0-rc1

PyCall latest master
PyPlot latest master

Python 2.7.10 downloaded with Anaconda

```
ENV["PYTHON"] = "c:\\Anaconda\\python.exe"
```

Thanks for fixing the problems!

**Comment by stevengj** [comment]
Great, I will tag a new PyCall version once I do some more tests.

**Comment by rickedanielson** [comment]
Only because it was the first thing to try, versions are current now (v"0.4.3-pre+4", PyCall 1.2.0+ master, PyPlot 2.1.1+ master).  However, PyCall only stopped complaining after an explicit rebuild, as in

Pkg.build("PyCall")
Pkg.test("PyCall")
