### ISSUE TITLE
WARNING: could not import Base.help into PyCall  

### ISSUE THREAD

**Issue by dbrowne** [stevengj/PyCall.jl#183]
julia> using PyCall
WARNING: could not import Base.help into PyCall
version(true)
Julia Version 0.4.0-pre+7113
Commit 092bcf4* (2015-08-31 17:47 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  uname: Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 i386
.
.
.
 - PyCall                        0.8.2
 - PyPlot                        2.0.1

**Comment by stevengj** [comment]
Should be fixed in `master`.
