### ISSUE TITLE
ERROR: LoadError: LoadError: could not load symbol "PyCObject_FromVoidPtr"

### ISSUE THREAD

**Issue by davidanthoff** [stevengj/PyCall.jl#185]
I only get this when testing https://github.com/davidanthoff/ExcelReaders.jl with Python 3.4 on Windows x86 on appveyor with the current julia 0.4 nightlies. You can see the [log here](https://ci.appveyor.com/project/davidanthoff/excelreaders-jl/build/job/306yjqc6cjl0qd3x).

I'm pretty sure this has nothing to do with my package, and probably #182 would help with catching those kinds of problems at the source.

**Comment by swt30** [comment]
Same as #178 and/or #173? @davidanthoff, does it help if you add `Pkg.build("PyCall")` immediately before PyCall is loaded in the test? I have been having a similar issue with Python 3.4 on Linux, which can be avoided either by building PyCall during the same session before it's loaded or hacking in an extra `Libdl.dlopen` call during the init step, but I still have basically no idea why that's helping.

**Comment by stevengj** [comment]
This should be fixed now, I think?  Tests are passing with Python 3.x now on Mac and Windows...

**Comment by davidanthoff** [comment]
Yes, all passing, thanks a lot!
