### ISSUE TITLE
Make PyCall work with Conda.jl

### ISSUE THREAD

**Issue by dhoegh** [stevengj/PyCall.jl#190]
It would be nice if PyCall work out of the box with the miniconda installation provided by Conda.jl.

**Comment by stevengj** [comment]
That's an option, but it should probably only happen if there is not already a `python` found in the system.   If the user has already installed `python` then we should assume that's the python she wants to call.  (So, basically this may only be for Windows...)

The procedure might be:
* Add Conda to the `REQUIRE` file
* In `Pkg.build`, if `python` is not found, then tell Conda to install Python, and finish the build with Conda's `python`.

**Comment by stevengj** [comment]
See #191.

**Comment by dhoegh** [comment]
The problem with requiring Conda  is that Conda will always install a Minoconda distribution even for the users using the system wide python distribution. I thought it would be okay to require the user to add Conda and hence install miniconda. Then if Conda is installed then use it.

**Comment by stevengj** [comment]
Conda should install everything in its own path, so that it's not visible outside Julia.  If it's not doing that, then it seems wrong to me.

**Comment by dhoegh** [comment]
Ok. I was worried about the disk foot print of the Miniconda installtion, but if you think it is ok then I will fix the PR's accordingly. I my amount of spare time is not huge so they will only progress slowly over the next week.

**Comment by stevengj** [comment]
It's hard to believe the disk footprint could possibly be an issue these days.  I assume it's well under a GB?

**Comment by dhoegh** [comment]
Closed by #191
