### ISSUE TITLE
PyCall seems to ignore a function in theano called function

### ISSUE THREAD

**Issue by zenna** [stevengj/PyCall.jl#197]
I've been trying to use PyCall to wrap [theano](http://deeplearning.net/software/theano/index.html).  I started with the simple example from the tutorial

```python
>>> import theano.tensor as T
>>> from theano import function
>>> x = T.dscalar('x')
>>> y = T.dscalar('y')
>>> z = x + y
>>> f = function([x, y], z)
```

However, if I do

```julia
@pyimport theano.compile.function as func
```

`func` has no method `function`.  It does seem to have all the other methods defined in the python file.
Is it possibly because of the naming, that the word `function` is causing the problem?

**Comment by stevengj** [comment]
Yes, it's a reserved word in Julia so it can't be a member name of the imported module.  As described in the README, one must use `func.pymember(:function)` instead.
