### ISSUE TITLE
conda is installed regardless of the presence of python in PATH

### ISSUE THREAD

**Issue by r5r3** [stevengj/PyCall.jl#198]
I have a proper python installation and it is also included in my PATH variable. PyCall makes use of this installation during build:
`INFO: Building PyCall`
`INFO: PyCall is using python (Python 2.7.10) at /opt/anaconda3/envs/python27/bin/python, libpython = /opt/anaconda3/envs/python27/lib/libpython2.7.dylib`

Everything works fine with this installation. But the Conda package is installed anyway, which is in this context useless. How to avoid the installation of Conda if python is already present?

Background: I have a file number quota in my home directory (max. 100000 files). The useless conda installation adds neary 8000 files.

**Comment by stevengj** [comment]
@Luthaf, is there any chance that Conda could install itself lazily?

That is, only call `_install_conda()` the first time `Conda.add` or similar is invoked, not in `Pkg.build`.

**Comment by Luthaf** [comment]
This is where conditional dependency could be usefull!

**Comment by r5r3** [comment]
Another possibility would be that the Conda package scans the PATH for already present anaconda or miniconda installations. In case something is found, it could use this installation instead for creating its own.

**Comment by stevengj** [comment]
@r5r3, no, the whole point of Conda is to create an isolated Julia miniconda installation, independent of what users have installed on their systems.   Using a global anaconda install is not nearly as reliable, because there is no way to control what users have done with it (e.g. it could be out-of-date, or broken, or set up in other weird ways).

**Comment by r5r3** [comment]
@stevengj,  Ok, I understand that it is desirable to have an independent installation that is fully controlled by the Conda package. But that could by problematic for users with space limitations, e.g. students with university accounts belong almost always to this user group. I would expect that users with a quota on their home directories are not a minority. 

From this point of view, the lazy installation of the Conda package would likely be a good solution.

**Comment by stevengj** [comment]
This is fixed by Luthaf/Conda.jl#14.  Once @Luthaf tags a new version, you can just `rm(joinpath(Pkg.dir("Conda"),"deps","usr"), recursive=true)` to delete the miniconda installation, and it won't come back unless a package actually needs it.

**Comment by Luthaf** [comment]
> @Luthaf tags a new version

https://github.com/JuliaLang/METADATA.jl/pull/3533
