### ISSUE TITLE
Can't build PyCall in julia v0.4-rc3

### ISSUE THREAD

**Issue by augustot2** [stevengj/PyCall.jl#200]
while using the julia release candidate 3 in a separete folder, I can't build PyCall. The following is showing:
>> Pkg.add("PyCall")
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Conda from git://github.com/Luthaf/Conda.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of HttpCommon from git://github.com/JuliaWeb/HttpCommon.jl.git
INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
INFO: Cloning cache of PyCall from git://github.com/stevengj/PyCall.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Installing BinDeps v0.3.18
INFO: Installing Compat v0.7.5
INFO: Installing Conda v0.1.7
INFO: Installing Dates v0.4.4
INFO: Installing HttpCommon v0.2.4
INFO: Installing JSON v0.4.6
INFO: Installing PyCall v1.1.2
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.0
INFO: Building PyCall
INFO: Precompiling module Compat...
==================================================================[ ERROR: PyCall ]===================================================================

LoadError: could not spawn `/home/augusto/bin/julia4beta/bin/julia -Cx86-64 -J/home/augusto/bin/julia4beta/lib/julia/sys.so --output-ji /home/augusto/.julia/lib/v0.4/Compat.ji --output-incremental=yes --startup-file=no --history-file=no --eval 'while !eof(STDIN)
    eval(Main, deserialize(STDIN))
end
'`: no such file or directory (ENOENT)
while loading /home/augusto/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 11

======================================================================================================================================================

===================================================================[ BUILD ERRORS ]===================================================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/augusto/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

======================================================================================================================================================
INFO: Package database updated

**Comment by stevengj** [comment]
What happens if you type "using Compat" in Julia?  That seems to be the source of the error message.

**Comment by augustot2** [comment]
hi steven, this happens

julia> using Compat
INFO: Precompiling module Compat...
ERROR: could not spawn `/home/augusto/bin/julia4beta/bin/julia -Cx86-64 -J/home/augusto/bin/julia4beta/lib/julia/sys.so --output-ji /home/augusto/.julia/lib/v0.4/Compat.ji --output-incremental=yes --startup-file=no --history-file=no --eval 'while !eof(STDIN)
    eval(Main, deserialize(STDIN))
end
'`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:255
 in anonymous at process.jl:408
 in setup_stdio at process.jl:396
 in spawn at process.jl:407
 in open at process.jl:476
 in create_expr_cache at loading.jl:336
 in compilecache at loading.jl:382
 in require at ./loading.jl:250

**Comment by stevengj** [comment]
Does `/home/augusto/bin/julia4beta/bin/julia` exist?  Maybe you renamed `julia` or something?

(In any case, closing here as this is not a PyCall issue `per se`.  If you can't figure it out, I would file a Julia issue with a title like *Could not spawn julia process when precompiling*.)

**Comment by augustot2** [comment]
Sorry you were right, the solution was to rename the julia4beta to the original name julia! Thanks
