### ISSUE TITLE
Is there a way to enumerate all functions within the python library?

### ISSUE THREAD

**Issue by sbromberger** [stevengj/PyCall.jl#203]
My python library consists of compiled shared objects so enumeration of objects and methods is very difficult (the source is C++). I'd like to create Julia bindings for the entire library of the form `Obj.method(args...) = method(Obj, args...)`. I'm pretty sure I can do this with a macro that translates the bracket calling convention, but is there a way to do a wholesale port?

**Comment by stevengj** [comment]
You can use the Python `inspect` module to get the list of methods in a library etc.   However, you would have to be careful about automating the generation of Julian wrappers like this, e.g. what if a method name conflicts with a method name in Julia Base?

**Comment by sbromberger** [comment]
Thanks, @stevengj - this was probably a better question for -users. The names will likely not conflict - because they're basically C++, they use upper case and are very long.
