### ISSUE TITLE
No virtualenv path, Julia 0.4

### ISSUE THREAD

**Issue by multidis** [stevengj/PyCall.jl#205]
Just tried PyCall after updating Julia to 0.4, and  `virtualenv` path elements are not showing up (as opposed to how things worked in Julia 0.3 on the same machine). Import error is returned for any package installed in virtualenv but not system-wide.

More specifically, after sourcing virtualenv's activate:

    import sys
    sys.path

Returns both system-wide and virtualenv-specific path entries, while

    julia
    using PyCall
    @pyimport sys
    sys.path

(or `PyVector(pyimport("sys")["path"])`) returns only those path entries that are available system-wide and none from the virtualenv.

NOTE: Running commands not from the virtualenv-directory itself, so `unshift!(PyVector(pyimport("sys")["path"]), "")` does not help.

**Comment by stevengj** [comment]
The new version of PyCall determines what Python library and path to use at build-time, rather than each time it starts up as in the older version.  This enables to benefit from precompilation.  However, it means that switching to/from a virtualenv will not affect PyCall unless you rebuild PyCall.

Make sure you run `Pkg.build("PyCall")` after setting up the virtualenv.

**Comment by multidis** [comment]
Makes sense, although a bit inconvenient when multiple virtualenvs are to be used (which seems to be a common practice instead of modifying system-wide python setup per project).

After rebuilding the package from inside virtualenv path entries are correct and everything works, thanks for pointing it out. I did have to manually delete `~/.julia/v0.4/PyCall` though since just `Pkg.build("PyCall")` was not sufficient (same system-wide path was used).

**Comment by stevengj** [comment]
It remembers the name of the `PYTHON` executable so that it doesn't suddenly switch pythons on you if you do `Pkg.update()`.   But you can just set `ENV["PYTHON"]="python"; Pkg.build("PyCall")` (or whatever the name of your Python is) to reset.

**Comment by stevengj** [comment]
This is described in https://github.com/stevengj/PyCall.jl#specifying-the-python-version

Although the issue of virtualenvs could be clarified.
