### ISSUE TITLE
Couldn't find libpython in a virtualenv

### ISSUE THREAD

**Issue by ftzeng** [stevengj/PyCall.jl#206]
I'm receiving this error when trying to build PyCall:

```
LoadError: Couldn't find libpython; check your PYTHON environment variable
while loading /home/ftseng/.julia/v0.4/PyCall/deps/build.jl, in expression starting on line 17
```

I have a 64-bit Python 3.5 installation in a virtualenv. I have the virtualenv activated and am specifying the path to the Python executable manually:

```
export PYTHON=$(which python)
```

But when I run `Pkg.build("PyCall")` I still get that error. Is there something else I need to configure?

My `versioninfo()`:

```
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by stevengj** [comment]
What Python distro are you using?

**Comment by ftzeng** [comment]
The official CPython distribution (3.5), built from source.

**Comment by stevengj** [comment]
Maybe edit `build.jl` to make the last line of `find_libpython`:
```jl
error("Couldn't find libpython (tried $libs in $libpaths); check your PYTHON environment variable")
```
to see what library names and paths it is trying.   (Compare to where your actual `libpython` is.)

**Comment by ftzeng** [comment]
Thanks for your guidance - the issue is that I did not configure my Python build with `--enable-shared`. 

For reference, I rebuilt Python like so:

```
PYVERSION=3.5.0
wget https://www.python.org/ftp/python/${PYVERSION}/Python-${PYVERSION}.tar.xz -O /tmp/
cd /tmp
tar xfv Python-${PYVERSION}.tar.xz
cd Python-${PYVERSION}
./configure --prefix=/usr/local --enable-shared
LD_RUN_PATH=/usr/local/lib make
sudo make install
```

Then running `Pkg.build("PyCall")` worked without a problem.

**Comment by diwu93** [comment]
I met the same problem and have fixed it with your comments! Thank you so much!

**Comment by diwu93** [comment]
I met the same problem and have fixed it with your comments! Thank you so much! @frnsys
