### ISSUE TITLE
ENV["PYTHON'] does not build correctly to installed Python

### ISSUE THREAD

**Issue by lewisl** [stevengj/PyCall.jl#211]
I build PyCall by setting ENV["PYTHON"].  Note that PyCall finds and confirms that it finds a Python executable there.  Then when I do using PyCall note the failure to find the right Python--it looks in conda instead.  Note that I do not have a path set to this Python, but according to the readme, I can use ENV instead.  Perhaps that is wrong.  I will try again with path.

Note that I have spent (wasted) about 4.5 hours on this.  Note also that using conda no longer works. See problem reported on Julia Users yesterday, and confirmed  several times.  All works fine on Mac.  I realize developers don't like working on Windows; it IS frustrating.  But, if Julia intends to run on Windows (with some charting), then it is a duty (painful as it may be...).  

I'll report back if setting a path fixes this.  Each try takes more than 45' so I might not have time for a while.

**Comment by lewisl** [comment]
Forgot to paste in the output

>
julia> ENV["PYTHON"]
"c:\\Python27\\python.exe"

julia> Pkg.add("PyCall")
INFO: Installing BinDeps v0.3.19
INFO: Installing Compat v0.7.7
INFO: Installing Conda v0.1.8
INFO: Installing Dates v0.4.4
INFO: Installing JSON v0.5.0
INFO: Installing PyCall v1.1.2
INFO: Installing SHA v0.1.2
INFO: Installing URIParser v0.1.1
INFO: Building PyCall
INFO: PyCall is using c:\Python27\python.exe (Python 2.7.10) at c:\Python27\python.exe, libpython = pytho
n27
INFO: Package database updated

julia> ENV["PYTHON"]
"c:\\Python27\\python.exe"

julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: PyCall is using c:\Python27\python.exe (Python 2.7.10) at c:\Python27\python.exe, libpython = pytho
n27

julia> ENV["PYTHON"]
"c:\\Python27\\python.exe"

julia> using PyCall

julia> @pyimport matplotlib.pyplot as plt
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('DLL load failed: The specified module could not be found.',)
  File "C:\Users\Lewis\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\pyplot.py", line 27, in <m
odule>
    import matplotlib.colorbar
  File "C:\Users\Lewis\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\colorbar.py", line 34, in
<module>
    import matplotlib.collections as collections
  File "C:\Users\Lewis\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\collections.py", line 27,
in <module>
    import matplotlib.backend_bases as backend_bases
  File "C:\Users\Lewis\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\backend_bases.py", line 56
, in <module>
    import matplotlib.textpath as textpath
  File "C:\Users\Lewis\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\textpath.py", line 22, in
<module>
    from matplotlib.mathtext import MathTextParser
  File "C:\Users\Lewis\.julia\v0.4\Conda\deps\usr\lib\site-packages\matplotlib\mathtext.py", line 63, in
<module>
    import matplotlib._png as _png

 [inlined code] from C:\Users\Lewis\.julia\v0.4\PyCall\src\exception.jl:81
 in pyimport at C:\Users\Lewis\.julia\v0.4\PyCall\src\PyCall.jl:79

**Comment by lewisl** [comment]
Good news:  adding path to the external Python solves the build problem.  

Will close the  issue:  should I do pull req on documentation:  it could make the point explicit.  It's not surprising.

**Comment by stevengj** [comment]
It is surprising. I don't understand why modifying PATH should be necessary. It's not needed on other platforms.
