### ISSUE TITLE
keys(O::PyObject) error

### ISSUE THREAD

**Issue by egoecho** [stevengj/PyCall.jl#212]
I found keys(PyObject) will trigger an error. For example:
julia> using PyPlot

julia> fig=figure()
PyPlot.Figure(PyObject <matplotlib.figure.Figure object at 0x7f57705eabd0>)

julia> keys(fig)
ERROR: TypeError: PyVector: in parameter, expected Type{T}, got Tuple{DataType,DataType}                                                                                 
in keys at /home/jxiong/.julia/v0.4/PyPlot/src/PyPlot.jl:314

julia> ax=subplot(2,2,1)
PyObject <matplotlib.axes._subplots.AxesSubplot object at 0x7f57703ff4d0>

julia> keys(ax)
ERROR: TypeError: PyVector: in parameter, expected Type{T}, got Tuple{DataType,DataTy
pe}                                                                                 
 in keys at /home/jxiong/.julia/v0.4/PyCall/src/PyCall.jl:282

julia> matplotlib
PyObject <module 'matplotlib' from '/home/jxiong/anaconda/lib/python2.7/site-packages/matplotlib/__init__.pyc'> 

julia> keys(matplotlib)
ERROR: TypeError: PyVector: in parameter, expected Type{T}, got Tuple{DataType,DataType}                                                                                 
 in keys at /home/jxiong/.julia/v0.4/PyCall/src/PyCall.jl:282

**Comment by stevengj** [comment]
Thanks, this is a casualty of the tupocalypse in 0.4; I'll fix it shortly.
