### ISSUE TITLE
A Git warning occuring only witn PyCall in `Pkg.update`

### ISSUE THREAD

**Issue by zhujinxuan** [stevengj/PyCall.jl#213]
I am not sure whether I shall report it here or on JuliaLang/julia.  Recently, when I run `Pkg.update()`, There is an warning which only exists about PyCall.
```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating PDMats master...
INFO: Updating Met_Plots_Models master...
WARNING: fetch: GitError(Code:ERROR, Class:Net, Unsupported URL protocol)
INFO: Updating Met_Basic_Types master...
INFO: Updating PyCall master...
WARNING: fetch: GitError(Code:ERROR, Class:Net, Unsupported URL protocol)
INFO: Updating NonlinearSpectralModels master...
INFO: Updating Compose master...
INFO: Updating DataArrays master...
INFO: Updating PyPlot master...
INFO: Updating Gadfly master...
INFO: Updating NetCDF master...
INFO: Updating DataFrames master...
INFO: Computing changes...
INFO: No packages to install, update or remove
```

The `Unsupported URL protocol` occurs only with PyCall and another package written for myself...  I am not sure whether there are some git configs in PyCall about this warning

My julia version follows here, and I install the PyCall by `Pkg.checkout()`
```
julia> versioninfo()
Julia Version 0.5.0-dev+1165
Commit bbec291 (2015-11-06 20:40 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libm
  LLVM: libLLVM-3.7.0
```

Thank you.

**Comment by stevengj** [comment]
The [PyCall url](https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/PyCall/url) is a `git://` URL, the same as all other package URLs, so I don't know why there would be a problem only with PyCall.

Does it give a warning if you manually `git clone git://github.com/stevengj/PyCall.jl.git`, or do a `git fetch` once it is cloned?

**Comment by zhujinxuan** [comment]
The error disappears after removing and reinstalling PyCall. I think I had made some mistakes about it though I do not know what mistakes I have made.

You can close the issue if you like.  Sorry for wasting your time.

**Comment by zhujinxuan** [comment]
I find how it happens

If I install PyCall with `Pkg.add("PyCall")`, then the error will not appear.

But if I use `Pkg.checkoyt("PyCall")`, then the error will appear

**Comment by zhujinxuan** [comment]
Sorry, my mistake. 

I find that the error will not occur when I remove all unregistered packages in .julia/v0.5

Sorry for wasting your time.
