### ISSUE TITLE
Converting python string objects to Vector{UInt8}

### ISSUE THREAD

**Issue by phobon** [stevengj/PyCall.jl#215]
Right now it seems I cannot smoothly convert a python string to an array of bytes without an extra conversion to `ASCIIString` first. Can this be supported? Is it something that only makes sense in Python 2?

Thanks!

```
julia> using PyCall

julia> pystr = convert(PyObject, "\x01\x02\x03")
PyObject '\x01\x02\x03'

julia> convert(Vector{UInt8}, pystr)
ERROR: PyError (PyInt_AsSsize_t) <type 'exceptions.TypeError'>
TypeError('an integer is required',)

 [inlined code] from /home/jdlangs/.julia/v0.5/PyCall/src/exception.jl:56
 in convert at /home/jdlangs/.julia/v0.5/PyCall/src/conversions.jl:31
 in py2array at /home/jdlangs/.julia/v0.5/PyCall/src/conversions.jl:350
 in convert at /home/jdlangs/.julia/v0.5/PyCall/src/conversions.jl:401
 in eval at ./boot.jl:264

julia> convert(Vector{UInt8}, convert(ASCIIString, pystr))
3-element Array{UInt8,1}:
 0x01
 0x02
 0x03
```

**Comment by stevengj** [comment]
I should really update teh `convert(Vector{UInt8}, ...)` method to use the newer PyBuffer code, which will make it more general and should fix this.

**Comment by stevengj** [comment]
Note, however, that in general with interpreting Python strings as byte arrays, you have to be cautious about encoding differences—for Unicode strings, my understanding is that Python may choose different encodings under the hood.

**Comment by phobon** [comment]
Thanks for the super-fast response!

The library I'm using is deliberately using a string for arbitrary byte storage so I expect I should be ok not worrying about encodings.
