### ISSUE TITLE
Generators broken with collect

### ISSUE THREAD

**Issue by oxinabox** [stevengj/PyCall.jl#216]
I do believe that generators are  broken now.
As of https://github.com/stevengj/PyCall.jl/commit/8ab1d88ffe946e220fc5279fe9b08aa2186a0cf2
I think (I haven't done a bisect)

MWE:

```
@pyimport itertools
xs = (itertools.combinations([1,2,3],2))
collect(xs)
```

Errors with:

```
LoadError: PyError (:PySequence_Size) <type 'exceptions.TypeError'>
TypeError("object of type 'itertools.combinations' has no len()",)

while loading In[32], in expression starting on line 3

 [inlined code] from /home/ubuntu/.julia/v0.5/PyCall/src/exception.jl:82
 in length at /home/ubuntu/.julia/v0.5/PyCall/src/PyCall.jl:451
 in collect at array.jl:243
 in collect at array.jl:262
```

Array comprehensions also throw an exception (eg  `[i for i in xs]`)
 with the same message (though I don't think that has ever worked -- it wouldn't work for a regular julia iterator)

---
On the other hand 

```
xst = []
for i in xs
    push!(xst, i)
end
```

works fine. So the work around is  apparent.

But `collect` used to work.

**Comment by stevengj** [comment]
Hmm, that's because `collect` tests `applicable(length, itr)`.  Might be easiest just to write a `collect(o::PyObject)`.

**Comment by stevengj** [comment]
Looks like this was broken again by JuliaLang/julia@a2ce2309863564aed3fba4f8927d586b11983219, since `collect(x)` no longer calls `collect(T, x)`.
