### ISSUE TITLE
Broken interface between PyCall and SimpleJson

### ISSUE THREAD

**Issue by mwojnowicz** [stevengj/PyCall.jl#224]
When I run @pyimport my_python_module_name, I get an error message about importing simplejson, as per below:

    ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
    ImportError('No module named simplejson',)

Even though simplejson is updated and successfully imports in ipython.

Versions:
OS: Linux (Red Hat 4.8.2-16)
Simplejson: 3.8.1
Julia: v"0.3.8-pre+22"
Python: 2.7.10

**Comment by stevengj** [comment]
Are you sure that PyCall is set up to use the same Python version?  What is the output of `Pkg.build("PyCall")`?

**Comment by mwojnowicz** [comment]
Good point. 
    Pkg.build("PyCall") 
reveals that PyCall is using Python version 2.7.11, but the python call 
    sys.version_info
suggests that Python is running 2.7.10.    

I can probably Google up a solution, but while we're both here, any quick suggestions?
