### ISSUE TITLE
Is there any possible way to use Pillow module?

### ISSUE THREAD

**Issue by xanadupark** [stevengj/PyCall.jl#225]
Hello,
I tried to use PyCall to call fuctions in Pillow (PIL).
What I really want to do is generating a image and drawing some lines on that image.
Here is what I have done:
```
julia> using PyCall

julia> @pyimport numpy as np

julia> @pyimport PIL.Image as pimg

julia> img = pimg.new('L', (100,100), 255)
ERROR: PyError (:PyObject_Call) <class 'TypeError'>
TypeError('must be str, not PyCall.jlwrap',)
  File "C:\Miniconda3\lib\site-packages\PIL\Image.py", line 2012, in new
    return Image()._new(core.fill(mode, size, color))

 [inlined code] from C:\Users\10189524\.julia\v0.4\PyCall\src\exception.jl:81
 in pycall at C:\Users\10189524\.julia\v0.4\PyCall\src\PyCall.jl:361
 in call at C:\Users\10189524\.julia\v0.4\PyCall\src\PyCall.jl:388
```
Is there any workaround for this?
My environment is:
MS windows 7
julia 0.4.2
python 3.5.1
pillow 3.0.0

The python was installed by Miniconda.

Thanks in advance

**Comment by stevengj** [comment]
Strings in Julia use double quotes, `"L"`.  The single-quoted expression `L` in Julia is a character constant, which has no direct equivalent in Python.
