### ISSUE TITLE
PyCall 1.3.0, redefining constant libpythondl

### ISSUE THREAD

**Issue by PaulSoderlind** [stevengj/PyCall.jl#229]
Hi, 
the latest PyCall 1.3.0 (as of 5 Feb 2016) gives the following warning: "redefining constant libpythondl" repeatedly whenever I use PyPlot or ExcelReaders.

on Julia 0.4.3, windows 7 (64)

**Comment by stevengj** [comment]
Possibly caused by #219; cc @benmoran.

**Comment by dhoegh** [comment]
I do also see this on windows.

**Comment by PaulSoderlind** [comment]
Thanks for looking into this. It's a bit annoying to get that warning 
thousands of time when trying to do a bunch of plots.

Also, thanks a lot for you great packages.

Paul Söderind
