### ISSUE TITLE
LLVM error on worker processes

### ISSUE THREAD

**Issue by augustinyiptong** [stevengj/PyCall.jl#231]
Hi, i am getting the error below. No issues on single process.

Thanks, Gus

julia> addprocs(2)
2-element Array{Int64,1}:
 2
 3

julia> @everywhere using PyCall
LLVM ERROR: Program used external function 'julia_Type_1262' which could not be
resolved!
LLVM ERROR: Program used external function 'julia_Type_1307' which could not be
resolved!
Worker 2 terminated.
Worker 3 terminated.ERROR (unhandled task failure): readcb: connection reset by
peer (ECONNRESET)
ERROR: ProcessExitedException()
 in yieldto(Base.#yieldto, Task, Any) at .\task.jl:73
 in wait(Base.#wait) at .\task.jl:354
 in wait(Base.#wait, Condition) at .\task.jl:273
 in wait(Base.#wait, Channel{Any}) at .\channels.jl:67
 in take!(Base.#take!, Channel{Any}) at .\channels.jl:55
 in take!(Base.#take!, Base.RemoteValue) at .\multi.jl:904
 in remotecall_fetch(Base.#remotecall_fetch, Any, Base.Worker) at .\multi.jl:798

 in remotecall_fetch(Base.#remotecall_fetch, Any, Int64) at .\multi.jl:803
 in #2(##2#4) at .\multi.jl:1484

...and 2 other exceptions.

 in sync_end(Base.#sync_end) at .\task.jl:397
 in anonymous at .\multi.jl:1493
 in eval(Core.#eval, Module, Any) at .\boot.jl:267

ERROR (unhandled task failure): readcb: connection reset by peer (ECONNRESET)

julia> versioninfo()
Julia Version 0.5.0-dev+2440
Commit 2bb94d6 (2016-02-01 02:22 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1

**Comment by yuyichao** [comment]
This happens before https://github.com/JuliaLang/julia/pull/15300 but is very similar to https://github.com/JuliaLang/julia/issues/14735 and is very likely fixed now.

**Comment by stevengj** [comment]
Thanks, @yuyichao.  Closing unless this can be reproduced with the latest master.
