### ISSUE TITLE
@pyimport throws error if PyPlot is loaded

### ISSUE THREAD

**Issue by crbinz** [stevengj/PyCall.jl#238]
Came into work today to find my code has stopped working, and narrowed it down to this:

First, working:
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using PyCall

julia> @pyimport mayavi.mlab as mlab

```

But if I load PyPlot first:
```
julia> using PyPlot, PyCall

julia> @pyimport mayavi.mlab as mlab
ERROR: PyError (:PyImport_ImportModule) <type 'exceptions.NotImplementedError'>
NotImplementedError("the qt4 pyface backend doesn't implement PyfaceResourceFact                                   ory",)
```

The full error message is long, so I put it [here](https://gist.github.com/crbinz/2a0751faff764305406e). I suspect this may be something to do with Python installations (miniconda vs. system, etc.), but idk. Thanks in advance.

**Comment by stevengj** [comment]
Possibly Matplotlib and Mayavi are fighting over the Qt backend... maybe they can't both use Qt at the same time?  You could always initialize Matplotlib using a different backend.

**Comment by crbinz** [comment]
In fact my current workaround is to just import Mayavi first. Still, it would be nice to not have to worry about this.

**Comment by stevengj** [comment]
Does the same thing happen in Python?  If so, it is probably a Matplotlib issue.

**Comment by crbinz** [comment]
No (I think). At least, here's what I tried (I'm not a python user):
```
>>> import matplotlib
>>> matplotlib.use('qt4agg')
>>> import mayavi.mlab as mlab
```
No errors.

**Comment by stevengj** [comment]
@crbinz, I think you have to `import matplotlib.pyplot` after the `use` statement to actually start up the backend?

**Comment by crbinz** [comment]
Ok, tried that, and still no errors.

**Comment by stevengj** [comment]
Maybe it has to do with PyCall using PyQT rather than PySide?

https://github.com/stevengj/PyPlot.jl/blob/master/src/PyPlot.jl#L147-L162

You can override this by setting `PyDict(pyimport("matplotlib")["rcParams"])["backend.qt4"] = "pyside"`

**Comment by crbinz** [comment]
It looks like that was it. I've added this setting to my `.matplotlibrc` file. Thanks for  your help.

**Comment by stevengj** [comment]
Great!  Glad it is solved.
