### ISSUE TITLE
Ubuntu trusty testing on Travis

### ISSUE THREAD

**Issue by jdlangs** [stevengj/PyCall.jl#240]
Hello,

This is not an urgent issue but I thought it would be good to start tracking it and hopefully get it figured out in the near future. I tried switching Travis to their "Trusty Beta" environment and a couple of the jobs failed, including with a segfault. (Refs: [travis.yml diff](https://github.com/phobon/PyCall.jl/commit/bc04b6dd05ef795dc87772c11e06be41d7ed7c7b), [Travis results](https://travis-ci.org/phobon/PyCall.jl/builds/111332366)) This currently prevents me from testing my package on trusty. Hopefully there is a quick fix, or it's just a Travis bug that will get sorted out by itself.

cc: @tkelman 

Thanks,
Josh

**Comment by stevengj** [comment]
Any update on this?

**Comment by phobon** [comment]
Not on my end. I just reran the CI job and got the same results as before. It's pretty weird that `2.7` segfaults, `3.2` can't be found, and everything else works.

Have you had a chance to review the build logs and see any hints on where to look next? I'm definitely out of my depth if internal python functions are crashing.

**Comment by stevengj** [comment]
I'm still confused -- what Ubuntu version does the standard Travis CI build run on (which is passing for PyCall right now).

**Comment by tkelman** [comment]
12.04 by default, but you can ask for 14.04 by setting `dist: trusty`

**Comment by stevengj** [comment]
I don't see any obvious explanation in the build log, @phobon. :disappointed:

**Comment by stevengj** [comment]
@phobon, can you re-try this?

**Comment by phobon** [comment]
I rebased on the latest PyCall master and got the [same results](https://travis-ci.org/phobon/PyCall.jl/builds/135348432).

**Comment by jdlangs** [comment]
This appears to be [fixed now](https://travis-ci.org/jdlangs/PyCall.jl/builds/155394305), though don't ask me how it happened. @stevengj, is there any chance you would want to make this the default testing environment?

**Comment by stevengj** [comment]
I dunno, why not just stick with the default in Travis?

**Comment by jdlangs** [comment]
Yeah, I'm not aware of any particular benefit in switching. Closing this issue now.
