### ISSUE TITLE
*args support

### ISSUE THREAD

**Issue by raphapr** [stevengj/PyCall.jl#241]
Hello,

How pass a variable number of arguments to a function with PyCall?

e.g.

```
list = [1,3,4,5]
foo(*list)
```

I cannot do this on Julia.

Thanks,
Raphael.

**Comment by stevengj** [comment]
`foo(list...)` is the Julia syntax for this.  It works fine with PyCall.

**Comment by stevengj** [comment]
See: http://docs.julialang.org/en/latest/manual/functions/#varargs-functions
