### ISSUE TITLE
using Julia reserved names for Python keyword arguments

### ISSUE THREAD

**Issue by codles** [stevengj/PyCall.jl#242]
I would like to call the scipy function `scipy.interpolate.Rbf` with the argument `function = 'linear'`. But it gives the error `ERROR: LoadError: syntax: unexpected "="`. I think this is caused by the term function. Is there another way I can call this function with the keyword argument?

```julia
@pyimport scipy.interpolate as sp
rbf = sp.Rbf(x, y, c, function = "linear")
```

**Comment by stevengj** [comment]
Oh, good question, I didn't think about how to use reserved names for keywords.   Probably we should add an additional optional argument to the low-level `pycall` function (https://github.com/stevengj/PyCall.jl/blob/fcbe0be562d347843d107617ce178cfa70ed1a54/src/PyCall.jl#L343-L368) to specify this: just a dictionary of `names=>values`.

**Comment by yuyichao** [comment]
`julia> sp.Rbf(x, y, c; :function=>"linear")`

**Comment by stevengj** [comment]
Ah, thanks @yuyichao, I didn't realize that this syntax existed in Julia.

**Comment by codles** [comment]
Thank you
