### ISSUE TITLE
Choose between python 2 and python 3 aven after installation.

### ISSUE THREAD

**Issue by photonOli** [stevengj/PyCall.jl#244]
For now, `pyCall` will decide to use either `python2` or `python3` at installation time.

Is it possible to modify it after without reinstalling everything?

Most of the time, I prefer calling `python3`. But some time to time, I have to call `python2` because some modules work only for `python2` (e.g. `opencv`)

It would be nice to do something like that:

```julia
choosePyCallKernelVersion(2)
```

**Comment by stevengj** [comment]
You can do
```jl
ENV["PYTHON"]="python2"
Pkg.build("PyCall")
```
and then re-launch Julia.
