### ISSUE TITLE
importing PyCall via the rc file throws an LLVM error 

### ISSUE THREAD

**Issue by svaksha** [stevengj/PyCall.jl#246]
Hi, 

On Debian (testing), adding [PyCall](https://github.com/svaksha/yaksha/blob/master/home/.juliarc.jl#L84) to the juliarc file throws this LLVM error:

LLVM ERROR: Program used external function 'julia_getindex_23763' which could not be resolved!
</error>

I changed it to `using PyCall`, same error. Any ideas on how to import PyCall during startup?

Thanks in Advance!

PS: I am running Version 0.5.0-dev+3161 (2016-03-15 10:34 UTC) on Debian (testing). 
I tried building it again `Pkg.checkout("PyCall"); Pkg.build("PyCall")` but no luck.

**Comment by stevengj** [comment]
0.5 is not working right now with PyCall, apparently due to a Julia bug; see JuliaLang/julia#15300.
