### ISSUE TITLE
calling python object in julia way, e.g. method(obj, args)

### ISSUE THREAD

**Issue by novatena2015** [stevengj/PyCall.jl#264]
This is not an issue but a trick to call methods of a python object in a similar way as julia

currently we have to write `o[:method](args) `

we can call it with `:method(o, args)` by extending the Base.call function

`Base.call(method::Symbol, o::PyObject, args...) = o[method](args...)`

**Comment by stevengj** [comment]
This would certainly be possible, but I'd prefer to keep the syntax closer to Python, in order to make it easier to translate Python documentation into Julia code when calling a Python library.
