### ISSUE TITLE
Importing this module leads to LoadError that it is not installed

### ISSUE THREAD

**Issue by fusion809** [stevengj/PyCall.jl#266]
Hi,

I have tried importing this module using:

```
include(/path/to/PyCall.jl/src/PyCall.jl)
```

that returned:

```
LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
while loading /home/fusion809/GitHub/others/Julia/PyCall.jl/src/PyCall.jl, in expression starting on line 32
while loading In[10], in expression starting on line 3
```

then I tried importing this module with:

```
Pkg.build("PyCall")
```

and it returned:

```
LoadError: PyCall is not an installed package
while loading In[13], in expression starting on line 4
```

I am new to Julia so please forgive me if I made a trivial error when importing this module.

Thanks for your time,
Brenton

**Comment by stevengj** [comment]
Install PyCall with `Pkg.add("PyCall")`.   Then you can just do `using PyCall` .... no need to `include`.

(I'm guessing you are manually cloning the package yourself?   See http://docs.julialang.org/en/release-0.4/manual/packages/)
