### ISSUE TITLE
Listing attributes of a PyObject

### ISSUE THREAD

**Issue by staticfloat** [stevengj/PyCall.jl#277]
Is there a better way to list the attributes of a `PyObject` than this:

```julia
function dir(x::PyObject; exclude_private=true)
    if exclude_private
        return Symbol[Symbol(field) for field in filter(x -> x[1] != '_', pyeval("dir(x)", x=x))]
    else
        return Symbol[Symbol(field) for field in pyeval("dir(x)", x=x)]
    end
end
```

This is the method I've been using to explore Python objects from julia.  It would be amazing to somehow support tab completion of PyObjects, but I suppose that can't happen until we can truly override the `.` operator.

**Comment by stevengj** [comment]
I usually use the [inspect module](https://docs.python.org/2/library/inspect.html), which is already imported as `PyCall.inspect`.

For example:
```jl
using PyCall
o = PyObject(rand(3,3))
PyCall.inspect[:getmembers](o)
```
and you can get the member names in symbol form by `map(x -> symbol(x[1]), PyCall.inspect[:getmembers](o))`

**Comment by stevengj** [comment]
(I don't think the REPL [tab-completion code](https://github.com/JuliaLang/julia/blob/b45adc5a484a945bb18eee7727067c5155974bbd/base/REPLCompletions.jl#L20-L83) is sufficiently pluggable to insert custom tab completion on `o[:<tab>`, without patching Julia itself.)

**Comment by cstjean** [comment]
Also `keys(o)`

**Comment by stevengj** [comment]
Oh right, I forgot I added that in d1d07ccfdb28a232c4d6ce5ce74c41801df9dbce ... probably needs a README patch.
