### ISSUE TITLE
precompile and PyCall, method error for `|`

### ISSUE THREAD

**Issue by jverzani** [stevengj/PyCall.jl#280]
I think this is a different issue than #269. Sometime in the past 13 days, something has changed so that PyCall doesn't precompile. Here is the error I get after running `Pkg.update()` on a just downloaded nightly (Commit a0661a0 (0 days old master))

```
julia> using PyCall
INFO: Recompiling stale cache file /Users/verzani/.julia/lib/v0.5/PyCall.ji for module PyCall.

... cut out warnings on bytestring and WORD_SIZE ....

ERROR: InitError: MethodError: no method matching |(::UInt32, ::Void)
Closest candidates are:
  |(::Any, ::Any, ::Any, ::Any...)
  |(::BinDeps.SynchronousStepCollection, ::Any)
  |{T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8}}(::T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8}, ::T<:Union{Int128,Int16,Int32,Int64,Int8,UInt128,UInt16,UInt32,UInt64,UInt8})
  ...
 in PyCall.PyTypeObject(::String, ::Int64, ::PyCall.##20#21) at /Users/verzani/.julia/v0.5/PyCall/src/pytype.jl:270
 in pyjlwrap_init() at /Users/verzani/.julia/v0.5/PyCall/src/pytype.jl:387
 in __init__() at /Users/verzani/.julia/v0.5/PyCall/src/pyinit.jl:100
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:174
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at ./loading.jl:202
 in require(::Symbol) at ./loading.jl:332
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
during initialization of module PyCall
```

**Comment by stevengj** [comment]
The `PyTypeObject` constructor has just changed in #279 ... can you see if your problem still occurs with the latest `master`?

**Comment by jverzani** [comment]
Thanks! It is working now with the latest master.

On Tue, May 24, 2016 at 8:19 AM, Steven G. Johnson <notifications@github.com
> wrote:

> The PyTypeObject constructor has just changed in #279
> <https://github.com/stevengj/PyCall.jl/pull/279> ... can you see if your
> problem still occurs with the latest master?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stevengj/PyCall.jl/issues/280#issuecomment-221251142>
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu
