### ISSUE TITLE
Issue with openpyxl

### ISSUE THREAD

**Issue by kuangxiaolong** [stevengj/PyCall.jl#282]
I am trying to write excel in Julia and it seems that the best way is to use PyCall to call python packages. I installed PyCall and other packages like numpy and math worked when I use PyCall, however, when I use @pyimport openpyxl, it says ImportError('No module named openpyxl',).  

Then I noticed that perhaps I should link PyCall to my python directory and tried everything on this page but it still doesn't work. Any similar situations? How can I solve this issue? Thanks.

**Comment by cstjean** [comment]
I just tried this and it worked:

```julia
import Conda
Conda.add("openpyxl")
using PyCall
@pyimport openpyxl
```

Does it work for you? You can also try:

```julia
ENV["PYTHON"]=""; Pkg.build("PyCall")
```

Before rerunning the above code.

**Comment by stevengj** [comment]
`No module named openpyxl` simply means that openpyxl is not installed for the Python version that PyCall is configured to use.   Either switch Python versions (via `ENV["PYTHON"]=""`) as explained in the README, or install `openpyxl` as usual for Python.

I would do `pyimport_conda("openpyxl", "openpyxl")` to automate the installation process, as described in the README.

**Comment by kuangxiaolong** [comment]
It worked, thanks.
