### ISSUE TITLE
PyCall still fails to execute YAML!

### ISSUE THREAD

**Issue by montyvesselinov** [stevengj/PyCall.jl#285]
This fails with the latest version:

julia> Pkg.status("PyCall")
 - PyCall                        1.6.1

julia> Pkg.checkout("PyCall")
INFO: Checking out PyCall master...
INFO: Pulling PyCall latest master...
INFO: Removing Ipopt v0.2.2
INFO: Removing JuMP v0.13.2
INFO: Removing Lazy v0.10.1
INFO: Removing MathProgBase v0.5.0
INFO: Removing ReverseDiffSparse v0.5.5

@PyCall.pyimport yaml
f = open(filename)
yamldata = yaml.load(f) 
close(f)

RROR: LoadError: LoadError: PyError (:PyObject_Call) <type 'exceptions.RuntimeError'>
RuntimeError('Julia exception: UndefVarError(:istextio)',)
  File "/Users/ftuser/Library/Python/2.7/lib/python/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/Users/ftuser/Library/Python/2.7/lib/python/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/Users/ftuser/Library/Python/2.7/lib/python/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/Users/ftuser/Library/Python/2.7/lib/python/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/Users/ftuser/Library/Python/2.7/lib/python/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "PyCall.jl", line 1, in <lambda>

**Comment by cstjean** [comment]
Thank you for the bug report, sorry that the issue persisted. I just tried it on my machine:

```julia
Pkg.checkout("PyCall")

using PyCall

PyCall.@pyimport yaml
f = open("/Users/cedric/Julia/PyCall/.travis.yml")
yamldata = yaml.load(f)
close(f)
```

and it worked. Could you try it out on that .yml file, or post the yml file that you're using? It might also be a package issue, I'm not sure why your Pkg.checkout removed other packages. Pkg.status on my machine says that I'm on PyCall 1.6.2+ master. Also, maybe your precompilation cache is wrong, for whatever reason? I can't figure out how to delete it.

**Comment by stevengj** [comment]
(In general, it is better to comment on the old issue #274 rather than opening a new issue for the same symptoms.)

**Comment by stevengj** [comment]
Probably you need to run `Pkg.update()`?

**Comment by montyvesselinov** [comment]
I did Pkg.update() and now it works. Thank you very much!

**Comment by huckl3b3rry87** [comment]
I am getting a similar issue to this, I have done ``Pkg.uptate()``:
```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using PyCall

julia> @PyCall.pyimport yaml
ERROR: PyError (ccall(@pysym(:PyImport_ImportModule), PyPtr, (Cstring,), name)) <type 'exceptions.ImportError'>
ImportError('No module named yaml',)

Stacktrace:
 [1] pyerr_check at /home/febbo/.julia/v0.6/PyCall/src/exception.jl:56 [inlined]
 [2] pyerr_check at /home/febbo/.julia/v0.6/PyCall/src/exception.jl:61 [inlined]
 [3] macro expansion at /home/febbo/.julia/v0.6/PyCall/src/exception.jl:81 [inlined]
 [4] pyimport(::String) at /home/febbo/.julia/v0.6/PyCall/src/PyCall.jl:370

julia> Pkg.status("PyCall")
 - PyCall                        1.14.0
```
I think that it is likely that there is some sort of python version issue, but even after:
```
julia> Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /home/febbo/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /home/febbo/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /home/febbo/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: /home/febbo/.julia/v0.6/PyCall/deps/deps.jl has not changed
INFO: /home/febbo/.julia/v0.6/PyCall/deps/PYTHON has not changed
```
I still get this error. Also, all of the tests pass fine:
```
julia> Pkg.test("PyCall")
INFO: Testing PyCall
INFO: Python version 2.7.13 from /home/febbo/.julia/v0.6/Conda/deps/usr/lib/libpython2.7, PYTHONHOME=/home/febbo/.julia/v0.6/Conda/deps/usr:/home/febbo/.julia/v0.6/Conda/deps/usr
ENV[PYTHONPATH]=/home/febbo/Documents/workspace/tutorials/catographer_ws/install_isolated/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages
ENV[PYTHONHOME]=
ENV[PYTHONEXECUTABLE]=
INFO: Installing zmq via the Conda pyzmq package...
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/febbo/.julia/v0.6/Conda/deps/usr:

The following NEW packages will be INSTALLED:

    libsodium: 1.0.10-0     
    pyzmq:     16.0.2-py27_0
    zeromq:    4.1.5-0      

libsodium-1.0. 100% |###################################################| Time: 0:00:00   6.84 MB/s
zeromq-4.1.5-0 100% |###################################################| Time: 0:00:00  20.22 MB/s
pyzmq-16.0.2-p 100% |###################################################| Time: 0:00:00  22.35 MB/s
Fetching package metadata .........
Solving package specifications: .

Package plan for package removal in environment /home/febbo/.julia/v0.6/Conda/deps/usr:

The following packages will be REMOVED:

    pyzmq: 16.0.2-py27_0

INFO: PyCall tests passed
```
Maybe if this gets fixed we can trow it in the tests?

Thanks!

**Comment by stevengj** [comment]
@huckl3b3rry87, the behavior is correct.  If you configure PyCall to use Conda's Python, but install the package you are using (e.g. YAML) into the system Python, then it isn't going to work.  You have to install Python packages into the Python you are using with PyCall, or reconfigure PyCall to use a different Python.

**Comment by stevengj** [comment]
Since this comes up a lot, however, probably we should add more information to ImportError exceptions in `pyimport`.
