### ISSUE TITLE
Issues with Virtualenvs

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [stevengj/PyCall.jl#298]
I want to run `PyCall.jl` off a Python interpreter in a virtualenv. Thus:

    ENV["PYTHON"]="/Users/MyUsername/.virtualenvs/myvirtualenv/bin/"

So far, so good. However, calling `Pkg.build("PyCall")` yields

```
INFO: Building PyCall
INFO: No system-wide Python was found; got the following error:
could not spawn `/Users/MyUsername/.virtualenvs/myvirtualenv/bin/ -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`: permission denied (EACCES)
using the Python distribution in the Conda package
```

...and on it goes to install me a Miniconda, which is not what I wanted. The venv, of course, is totally accessible and owned by me, and so is the Julia executable (under `Applications`, on a Mac). I wonder why that happens?

**Comment by stevengj** [comment]
You need `ENV["PYTHON"]="/Users/MyUsername/.virtualenvs/myvirtualenv/bin/python" — the path of `python`, not the directory `python` lives in.

**Comment by chrisvoncsefalvay** [comment]
Duh. *NOW* I feel silly. Thanks, @stevengj. Apologies for cluttering up issues.
