### ISSUE TITLE
PYTHONHOME warning during precompile

### ISSUE THREAD

**Issue by stevengj** [stevengj/PyCall.jl#299]
When using the Conda Python, with PyCall `master`, I now get:
the following warning while precompiling:
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
```
This warning comes *before* we call `Py_SetPythonHome` to set PYTHONHOME.   It seems to be coming from `libpython` during the `startup.jl` code...

This seems to be a consequence of #293, cc @Keno.

The warning is probably harmless because we *do* eventually set PYTHONHOME in `__init__`, and the warning only comes when the `PyCall.ji` cache is stale, but it would be nice to get rid of it.

**Comment by stevengj** [comment]
Apparently, we need to call `Py_SetPythonHome` before we call `Py_GetVersion` to avoid the warning.  But you need to know the version in order to know the correct API for `Py_SetPythonHome`.  Grrr.

**Comment by Keno** [comment]
Can we check for the presence of some symbol to know what the correct API is?

**Comment by stevengj** [comment]
In startup.jl, I think we can just use `pyversion_build`.   In build.jl, we set the PYTHONHOME environment variable so we are fine there.

**Comment by Keno** [comment]
Sounds ok to me. I was briefly concerned about the pyjulia use case, but since Python would already be initialized, that shouldn't be a problem.

**Comment by stevengj** [comment]
Yeah, this only affects the non-pyjulia case.

**Comment by damiendr** [comment]
For some reason I got a `wPYTHONHOME not defined` error after updating PyCall via `Pkg.update()`. Indeed `build/deps.jl` had not been updated; this was fixed by calling `Pkg.build("PyCall")`. Not sure what went wrong, reporting this just in case!

**Comment by stevengj** [comment]
@damiendr, I'm guessing you have the `master` version of PyCall checked out.   When you do this, `Pkg.update` no longer calls `Pkg.build` automatically.  You can do `Pkg.free("PyCall")` to go back to using tagged versions.
