### ISSUE TITLE
could not load symbol "dladdr" while precompilling on 0.4.2

### ISSUE THREAD

**Issue by phlavenk** [stevengj/PyCall.jl#309]
The error appeared after running Pkg.update(). Happens during precompilation, build phase was OK.
The output listing:
```
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.status("PyCall")
 - PyCall                        1.7.0

julia> using PyCall
INFO: Precompiling module PyCall...
ERROR: LoadError: LoadError: error compiling anonymous: could not load symbol "d
laddr"
The specified procedure could not be found.

 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading c:\Users\phlavenk\JuliaData\v0.4\PyCall\src\startup.jl, in express
ion starting on line 42
while loading c:\Users\phlavenk\JuliaData\v0.4\PyCall\src\PyCall.jl, in expressi
on starting on line 37
ERROR: Failed to precompile PyCall to c:\Users\phlavenk\JuliaData\lib\v0.4\PyCal
l.ji
 in error at error.jl:21
```

**Comment by phlavenk** [comment]
Tested with pinned version 1.6.3. This tagged version runs without any problem. So it is specific to 1.7.0 only.

**Comment by stevengj** [comment]
The `dladdr` function is [only called](https://github.com/stevengj/PyCall.jl/blob/494f8316a868a24bbc09aa2626f0685ec939cf8e/src/startup.jl#L64-L65) if `is_windows()` returns `false`, and you are on Windows.  But maybe this needs to be `@static if is_windows()` so that the second branch isn't even compiled on Windows.

**Comment by phlavenk** [comment]
So it looks like it is related to #293 where the file startup.jl was added - it is failing there on line 64 in `ccall(:dladdr, Cint, (Ptr{Void}, Ptr{Dl_info}), some_address_in_libpython,  dlinfo)`

**Comment by phlavenk** [comment]
Yes, I can confirm that your proposal works!

**Comment by stevengj** [comment]
Okay, it should be fixed now if you do `Pkg.checkout("PyCall")` to get the `master` version.

**Comment by phlavenk** [comment]
Thank you Steven, the last commit works on Win64 0.4.2.
