### ISSUE TITLE
FYI: Python 3.6 (only in alpha now) - support later, but not now(?)

### ISSUE THREAD

**Issue by PallHaraldsson** [stevengj/PyCall.jl#310]
I was just looking over:

https://docs.python.org/3.6/whatsnew/3.6.html

[I assume you want to test on 3.6 when out, but do you feel you need before, or would that be premature/the testing system doesn't allow? Have new major releases posed any difficulty before? This is just a heads up.]

"Formatted string literals are a new kind of string literal, prefixed with 'f'. They are similar to the format strings accepted by str.format()."

Independently of whether PyCall.jl needs some extra support (I think not.., just making sure) then maybe Julia should adopt same syntax..

"New syntax features:

    PEP 498: Formatted string literals

Windows improvements:

    The py.exe launcher, when used interactively, no longer prefers Python 2 over Python 3"

"venv accepts a new parameter --prompt. This parameter provides an alternative prefix for the virtual environment
[..]
The pyvenv script has been deprecated in favour of python3 -m venv. This prevents confusion as to what Python interpreter pyvenv is connected to and thus what Python interpreter will be used by the virtual environment."

"[low level stuff] Checking if the GIL is held is also a new feature of Python 3.6."

There's more, I just copied what I though might possibly be problematic given what I see in the README.md:

"If you use Python virtualenvs, then be aware that PyCall uses the virtualenv it was built with
[..]
Type conversions are automatically performed for [..] string, IO stream
[..]

Julia IO streams are converted into Python objects implementing the RawIOBase interface, so they can be used for binary I/O in Python. However, some Python code (notably unpickling) expects a stream implementing the TextIOBase interface"

**Comment by stevengj** [comment]
There's always the possibility of difficulties.  However, the main question is whether they changed the C API.  Changes to pure Python syntax, like new string literals, don't affect PyCall.

**Comment by stevengj** [comment]
I'm going to close this.  If specific problems are identified with Python 3.6, they should get their own issue.  

Testing Python 3.6 prior to its release isn't a priority for me, as there should be plenty of time after it is released before it becomes widespread with PyCall users.   However, if you are motivated to test it now, please feel free.  Just do `ENV["PYTHON"]="/path/to/python3.6"; Pkg.build("PyCall"); Pkg.test("PyCall")`

**Comment by PallHaraldsson** [comment]
Ok. I did check out of curiosity and found:

const Py_hash_t = pyversion < v"3.2" ? Clong:Int

So at least you have one workaround (and of course 2 vs. 3). Python 3.2 is lowest 3.x tested; maybe not supported anymore.. should it be tested just in case (or stated not tested)?

[I'm not fully up to speed on e.g. virtualenvs, and how it relates to e.g. PyCall, I just mentioned just-in-case. Ok with closing. May test, I at least know now it's possible, but would testing now with Travis work automatically?]

**Comment by stevengj** [comment]
We test with all of the Python versions supported in Travis: https://docs.travis-ci.com/user/languages/python
