### ISSUE TITLE
Fix Travis error due to missing shared libraries.

### ISSUE THREAD

**Issue by stevengj** [stevengj/PyCall.jl#311]
The Travis tests are failing with Python 3.2 and 3.3, apparently because `libpython.so` is not installed.  (See the directory contents in the [build output](https://travis-ci.org/stevengj/PyCall.jl/jobs/152798549).)

Is there a `libpython-dev` package I need to install on Travis?

cc Travis gurus @staticfloat, @tkelman, @ninjin

**Comment by tkelman** [comment]
Probably. Travis builds their own Python in a slightly custom way if you use `language: python` from what I've heard. I don't know the details though.

**Comment by Keno** [comment]
From my pyjulia work, I know that those python installations are indeed dynamically linked, but don't ask me where those solibs are.

**Comment by stevengj** [comment]
Well, I've switched to `language: julia` since that makes it a lot easier to deal with different Julia versions, so now I'm relying on the Ubuntu python packages.  This only gives me Python 2.7 and 3.2 for now; I haven't yet found a reliable ppa for older Python versions on Ubuntu that supplies libpython.so (e.g. [this source only has python binaries](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes))

**Comment by tkelman** [comment]
could you use pyenv or something that builds python from source for you? I suspect `language: python` is harder to reimplement than `language: julia`, the latter is mostly downloading and extracting the binaries.
